/** Inline style map for the capture window; every colour is a theme token (see theme.tsx). */
import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000000,
    background: 'var(--ann-overlay)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    pointerEvents: 'auto',
  },
  card: {
    width: 'min(560px, calc(100vw - 32px))',
    maxHeight: '82vh',
    overflowY: 'auto',
    background: 'var(--ann-surface)',
    borderRadius: '12px',
    padding: '16px 18px',
    boxShadow: 'var(--ann-shadow)',
    color: 'var(--ann-text)',
    fontSize: '14px',
  },
  header: { display: 'flex', alignItems: 'center', gap: '8px', paddingBottom: '8px', borderBottom: '1px solid var(--ann-border)' },
  title: { fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1, minWidth: 0 },
  stepBadge: { fontSize: '12px', color: 'var(--ann-muted)', background: 'var(--ann-surface-alt)', borderRadius: '10px', padding: '2px 8px', whiteSpace: 'nowrap' },
  modeToggle: {
    border: '1px solid var(--ann-border)',
    background: 'transparent',
    color: 'var(--ann-text)',
    borderRadius: '10px',
    padding: '2px 10px',
    fontSize: '12px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  closeBtn: { border: 'none', background: 'transparent', cursor: 'pointer', fontSize: '14px', color: 'var(--ann-muted)' },
  sourceLine: { display: 'flex', alignItems: 'center', gap: '10px', margin: '8px 0 2px', flexWrap: 'wrap' },
  host: { fontSize: '12px', color: 'var(--ann-muted)' },
  linkBtn: { border: 'none', background: 'transparent', color: 'var(--ann-accent)', fontSize: '12px', cursor: 'pointer', padding: 0, textDecoration: 'underline' },
  kindRow: { display: 'flex', flexWrap: 'wrap', gap: '6px', margin: '10px 0' },
  kindChip: { border: 'none', borderRadius: '999px', padding: '4px 12px', fontSize: '13px', cursor: 'pointer' },
  restoredNote: { fontSize: '12px', color: 'var(--ann-muted)', marginBottom: '6px' },
  stepBody: { display: 'flex', flexDirection: 'column', gap: '8px', paddingTop: '10px' },
  stepTitle: { fontWeight: 600 },
  stepper: { display: 'flex', gap: '6px', alignItems: 'center', fontSize: '12px', color: 'var(--ann-muted)', paddingTop: '4px' },
  excerpt: { background: 'var(--ann-surface-alt)', borderRadius: '8px', padding: '8px 10px', lineHeight: 1.6, color: 'var(--ann-text)', wordBreak: 'break-word' },
  compareGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '8px' },
  textarea: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid var(--ann-border)',
    borderRadius: '8px',
    padding: '8px 10px',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'vertical',
    background: 'var(--ann-surface)',
    color: 'var(--ann-text)',
  },
  inlineTextarea: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid var(--ann-border)',
    borderRadius: '6px',
    padding: '6px 8px',
    fontSize: '13px',
    fontFamily: 'inherit',
    resize: 'vertical',
    background: 'var(--ann-surface)',
    color: 'var(--ann-text)',
  },
  label: { fontSize: '12px', color: 'var(--ann-muted)', marginTop: '2px' },
  compareLabel: { fontSize: '12px', color: 'var(--ann-muted)', marginBottom: '4px' },
  muted: { color: 'var(--ann-muted)', fontSize: '13px' },
  optionalBtn: {
    alignSelf: 'flex-start',
    border: '1px dashed var(--ann-border)',
    background: 'transparent',
    color: 'var(--ann-muted)',
    borderRadius: '8px',
    padding: '4px 10px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  optionalRow: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  verifyRow: { display: 'flex', alignItems: 'center', gap: '14px', flexWrap: 'wrap', fontSize: '13px' },
  confirmLabel: { display: 'flex', alignItems: 'center', gap: '6px', fontWeight: 600 },
  radioLabel: { display: 'flex', alignItems: 'center', gap: '4px' },
  verifiedNote: { background: 'var(--ann-success-bg)', color: 'var(--ann-success)', borderRadius: '8px', padding: '8px 10px', fontSize: '13px' },
  useError: { fontSize: '12px', color: 'var(--ann-danger)' },
  errorBanner: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
    background: 'var(--ann-danger-bg)',
    color: 'var(--ann-danger)',
    borderRadius: '8px',
    padding: '8px 10px',
    fontSize: '13px',
    wordBreak: 'break-word',
  },
  miniBtn: {
    border: '1px solid var(--ann-danger)',
    background: 'transparent',
    color: 'var(--ann-danger)',
    borderRadius: '6px',
    padding: '3px 8px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    fontSize: '12px',
  },
  checkRow: { display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px', color: 'var(--ann-text)' },
  select: { border: '1px solid var(--ann-border)', borderRadius: '8px', padding: '6px 8px', fontSize: '13px', background: 'var(--ann-surface)', color: 'var(--ann-text)' },
  tagInput: { border: '1px solid var(--ann-border)', borderRadius: '8px', padding: '7px 10px', fontSize: '13px', background: 'var(--ann-surface)', color: 'var(--ann-text)' },
  footer: { display: 'flex', alignItems: 'center', gap: '8px', paddingTop: '12px', marginTop: '10px', borderTop: '1px solid var(--ann-border)', flexWrap: 'wrap' },
  footerSpacer: { flex: 1 },
  primaryBtn: {
    background: 'var(--ann-accent)',
    color: 'var(--ann-accent-contrast)',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  ghostBtn: {
    background: 'transparent',
    color: 'var(--ann-text)',
    border: '1px solid var(--ann-border)',
    borderRadius: '8px',
    padding: '8px 14px',
    fontSize: '13px',
    cursor: 'pointer',
  },
  success: {
    background: 'var(--ann-success-bg)',
    color: 'var(--ann-success)',
    borderRadius: '10px',
    padding: '16px 28px',
    fontSize: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    alignItems: 'center',
    boxShadow: 'var(--ann-shadow)',
  },
  successActions: { display: 'flex', gap: '10px' },
  successLink: {
    background: 'transparent',
    color: 'var(--ann-success)',
    border: '1px solid var(--ann-success)',
    borderRadius: '8px',
    padding: '6px 14px',
    cursor: 'pointer',
    fontSize: '13px',
  },
  successPrimary: { background: 'var(--ann-success)', color: 'var(--ann-surface)', border: 'none', borderRadius: '8px', padding: '6px 14px', cursor: 'pointer', fontSize: '13px' },
  collapsedBar: {
    position: 'fixed',
    left: '50%',
    bottom: '16px',
    transform: 'translateX(-50%)',
    zIndex: 1000000,
    width: 'min(560px, calc(100vw - 32px))',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: 'var(--ann-surface)',
    color: 'var(--ann-text)',
    border: '1px solid var(--ann-border)',
    borderRadius: '10px',
    padding: '9px 14px',
    boxShadow: 'var(--ann-shadow)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontSize: '13px',
    pointerEvents: 'auto',
  },
  contextCard: { background: 'var(--ann-surface-alt)', borderRadius: '8px', padding: '8px 10px', lineHeight: 1.7, color: 'var(--ann-text)', wordBreak: 'break-word' },
  contextFaded: { opacity: 0.5 },
  contextMark: { background: 'var(--ann-mark)', color: 'inherit', borderRadius: '3px', padding: '0 2px' },
}
