import type { LandingCopy } from './types'

// English copy. It mirrors the Chinese page key for key (the type enforces it). Product terms follow
// docs/v2/README.md §4; strings inside the product windows follow utils/ui-text.ts of the extension. English is a
// preview until a native speaker has reviewed it (docs/v2/roadmap.md §6).
export const en: LandingCopy = {
  locale: 'en',
  meta: {
    title: 'AnnHub — Keep what’s worth keeping from the web in one local library',
    description: 'A local-first browser extension that keeps clips, highlights and screenshots with their source in one library, sorted by properties and exportable as Markdown.',
    ogTitle: 'AnnHub — A local-first library for clips, highlights and screenshots',
    ogDescription: 'Saving is easy. Finding it again, and telling it apart, is the hard part.',
    updated: '2026-10-09',
  },
  header: {
    nav: [
      { id: 'ways', label: 'Clip & screenshot' },
      { id: 'story', label: 'Workflow' },
      { id: 'library', label: 'Library' },
      { id: 'local', label: 'Local-first' },
      { id: 'faq', label: 'FAQ' },
    ],
    language: { label: '中文', href: '/zh-CN', aria: '切换到中文' },
    cta: 'Try the library',
    home: 'AnnHub home',
    skip: 'Skip to content',
    navLabel: 'Page sections',
  },
  hero: {
    chip: 'Browser extension · Local-first',
    lead: 'Keep what’s worth keeping from the web in one local library.',
    body: 'Clips, highlights and screenshots — with their source and properties — found again when you need them, and ready to take to Obsidian.',
    local: 'Local-first.',
    audience: 'Built for senior engineers, architects and tech leads',
    cta: 'Try the library',
    secondary: 'See the workflow',
    facts: ['Capture and export work offline', 'Data stays in your browser', 'Export Markdown; properties become frontmatter'],
    captions: { page: 'On the web · select a passage', reader: 'In the library · read, highlight, properties', library: 'In the library · clips and screenshots together' },
    sketch: 'Interface illustration based on the v2 design, using sample data',
  },
  problem: {
    title: 'Saving is easy. Finding it again, and telling it apart, is the hard part.',
    items: [
      {
        title: 'Scattered everywhere',
        body: 'Bookmarks, highlights and screenshots live in different tools and folders.',
        evidence: ['Bookmarks bar', 'Highlighter add-on', 'Screenshots folder'],
      },
      {
        title: 'Cut off from the source',
        body: 'All that’s left is a passage or an image. Which page was it from, and where on that page?',
        evidence: ['“Without a budget, every client retries at once.”', 'Which page?'],
      },
      {
        title: 'Hard to sort',
        body: 'With no shared tags or properties, finding anything depends on memory.',
        evidence: ['Screenshot 2026-09-14 10.40.png', 'retry notes (final) v2.md', 'Untitled (3)'],
      },
    ],
  },
  ways: {
    title: 'Two ways to keep it. Read it into your own in the library.',
    kinds: [
      {
        id: 'clip',
        name: 'Clip',
        body: 'Select a passage, or point at a whole article or post, and save it in one click.',
        caption: 'The selection menu, and the clip capsule that appears when you point at a whole block',
      },
      {
        id: 'screenshot',
        name: 'Screenshot',
        body: 'Drag or click to capture, annotate in place and mask identities.',
        caption: 'Annotations and the toolbar inside a screenshot selection',
      },
      {
        id: 'highlight',
        name: 'Highlight',
        body: 'Back in the library, read the clip, mark what matters and write down your thoughts. The original page is never touched.',
        caption: 'Select text in the library and pick a colour',
      },
    ],
    unified: {
      lead: 'They live in one library, share one set of properties, are searched together, and export as Markdown with `frontmatter`, with highlights written as `==…==`.',
    },
  },
  story: {
    title: 'From a technical article to a Markdown file with properties',
    intro:
      'An example: writing a design document for a payment retry strategy. Read and clip on Monday, organise in the library on Tuesday, find it again while writing on Thursday, take it with you on Friday.',
    steps: [
      {
        id: 'select',
        when: 'Mon 10:12',
        title: 'Select a passage, click “Clip”',
        body: 'One click saves it, and no window opens. For about 3 seconds you can undo, or add tags and a note right there.',
        caption: 'A passage selected in the article, with the Clip / Screenshot menu above it',
      },
      {
        id: 'block',
        when: 'Mon 10:20',
        title: 'Point at a whole section, click “Clip”',
        body: 'No selection needed: rest the pointer on the “Exponential backoff with jitter” section and a capsule appears. The whole section is saved as Markdown with its headings, list and link, and the page gets no mark.',
        caption: 'The pointer on a section: an outline and the clip capsule',
      },
      {
        id: 'shot',
        when: 'Mon 10:40',
        title: 'Drag around the latency curve, take a screenshot',
        body: 'Drag or click, then annotate in place and mask identities. Confirm to save it, or copy it into your design doc; the saved one stays untouched.',
        caption: 'Annotating inside the screenshot selection: the author masked, the spike circled',
      },
      {
        id: 'read',
        when: 'Tue 19:20',
        title: 'Back in the library: read it, mark what matters',
        body: 'Open the clip, select “jitter factor”, pick a colour and write a note. Highlights live only in the library. Then add tags and a project property.',
        caption: 'The reading view: highlights in the text, and the entry’s properties on the right',
      },
      {
        id: 'find',
        when: 'Thu 19:20',
        title: 'Search, filter by property, go back to the source',
        body: 'Search “idempotency”, then filter by project = Payments retry. The filters live in the address bar and survive a refresh. “Back to source” opens the original page to check.',
        caption: 'Search and property filter results in the library',
      },
      {
        id: 'export',
        when: 'Fri',
        title: 'Export Markdown, take it into Obsidian',
        body: 'One Markdown file per entry: properties are the frontmatter, highlights are written as `==…==`, images are stored once. Drop it into an Obsidian vault and it works.',
        caption: 'An exported Markdown file: properties in the frontmatter, highlights written as ==…==',
      },
    ],
    stepOf: '{n} / {total}',
    prev: 'Previous',
    next: 'Next',
    outro: 'Offline, capture, reading, search and export all keep working.',
  },
  tour: {
    title: 'Read, organise and find it again in the library',
    intro:
      'Every extension page is a left navigation with content on the right. However narrow the window gets, the navigation only folds into an icon rail; it never becomes a top bar.',
    hint: 'Try it: click the navigation, open an entry, press “Read”, then select text in the article to highlight it. Selecting with the keyboard and pressing H works too.',
    pins: [
      { title: 'Left navigation, content on the right', body: 'All, Clips, Highlights, Screenshots, Properties, Settings: every page shares one shell.' },
      { title: 'Every entry keeps its source', body: 'Type, title, source host, time, tags and properties sit in the row; a clip with highlights shows how many.' },
      {
        title: 'Highlights grouped by clip',
        body: 'Everything you marked lives in the Highlights view with its colour and note; click one to return to its place in the reading view.',
      },
      {
        title: 'Small, explicit properties',
        body: 'A property has a type, and one name means one type. Add it in the entry’s detail, manage it on the Properties page; on export it is the frontmatter.',
      },
      { title: 'One export command', body: '“Export content” packs the entries and their saved images into one ZIP for other tools to read.' },
    ],
    sketch: 'Interface sketch drawn from the v2 design; sample data',
  },
  diff: {
    title: 'A few deliberate choices',
    items: [
      {
        visual: 'entry',
        title: 'Not another bookmark list',
        body: 'Clips and screenshots are one kind of entry, each with its source, organised by type and properties. A highlight is a mark you make while reading a clip: it stays in the library and never touches the page.',
      },
      { visual: 'obsidian', title: 'No note app required', body: 'You get a complete library without Obsidian; and if you use it, the exported Markdown works as it is.' },
      { visual: 'properties', title: 'Properties stay small and explicit', body: 'They are typed, one name means one type, and long text goes in the note.' },
      { visual: 'offline', title: 'Local-first, and readable', body: 'The core loop works offline; entries and saved images export as a Markdown ZIP.' },
    ],
    offline: { label: 'Offline', steps: ['Capture', 'Read & highlight', 'Search & filter', 'Export Markdown'] },
    flow: { library: 'The library in your browser', zip: 'Markdown + original images ZIP', tool: 'Obsidian, or any tool that reads Markdown' },
  },
  trust: {
    eyebrow: 'Local-first',
    title: 'Your material shouldn’t be the price of using a tool',
    body: 'The extension keeps everything in your browser: entries and images in IndexedDB, settings and local counters in `chrome.storage`. There is no account, no AnnHub server and no AI service.',
    items: [
      { title: 'Works offline', body: 'Capture, reading, search, organising and export do not need a network.' },
      { title: 'Nothing uploaded by default', body: 'Page text, URLs, titles and what you organise are never sent to AnnHub or any third party.' },
      {
        title: 'Reads only what you point at',
        body: 'The extension reads a page only when you select text, point at a block or drag a screenshot, never anything you did not point at.',
      },
      {
        title: 'Yours to take',
        body: 'Export Markdown and your saved original images as one ZIP; properties become frontmatter. The ZIP is for reading in other tools; it is not a backup of the AnnHub database.',
      },
    ],
    exception: {
      title: 'The only outbound request',
      body: 'When you screenshot an element, the extension’s background fetches the cross-origin image that the page itself references, so the original can be saved: no credentials, public addresses only. Images inside a clip keep only their original address and are never loaded while you read.',
    },
    link: 'Read the privacy policy',
    diagram: {
      browser: 'Your browser',
      entries: 'IndexedDB · entries & images',
      settings: 'chrome.storage · settings & counters',
      server: 'AnnHub server',
      none: 'None',
      fetch: 'Fetches the page’s own image for a screenshot',
      page: 'The page you are reading',
    },
  },
  faq: {
    title: 'Frequently asked questions',
    lead: 'A few boundaries that matter.',
    items: [
      {
        q: 'How is AnnHub different from Obsidian Web Clipper?',
        a: 'Obsidian Web Clipper saves a web page as a note in your Obsidian vault, organised with templates and properties; it is free and open source. AnnHub puts clips and screenshots into a separate local library inside the browser, where you can also read a clip and highlight it, so you can read, search and organise without Obsidian — and export Markdown with properties and `==highlights==` for it.',
        note: 'The description of Obsidian Web Clipper was checked on 2026-10-07 against Obsidian’s official documentation.',
      },
      {
        q: 'How is it different from Readwise?',
        a: 'Readwise is a cloud reading and highlighting service. AnnHub keeps its data in your browser and covers clips, screenshots and highlights made in the library, searched by type and property.',
        note: 'The description of Readwise was checked on 2026-10-03 against its official pages.',
      },
      { q: 'Do I have to use Obsidian?', a: 'No. The library works inside the browser; the exported Markdown simply lets you take your material with you when you want to.' },
      { q: 'Where is my data stored?', a: 'In your browser’s local storage. Nothing is uploaded to an AnnHub server.' },
      {
        q: 'Why is there no mobile app?',
        a: 'AnnHub is designed for capturing, reading and organising in the desktop browser. There is no mobile app.',
      },
      {
        q: 'Can I export?',
        a: 'Yes. Click “Export content” in the extension to download a ZIP of Markdown files and your saved images, with properties written as frontmatter. It is meant for reading in other tools; it is not a backup that restores the AnnHub database.',
      },
    ],
  },
  closing: {
    title: 'Keep it close. Find it again.',
    body: 'Clips and screenshots enter one local library with their source. Read, highlight and find them by property, then export them as Markdown when you need to.',
    primary: 'Try the library',
    secondary: 'See the workflow',
  },
  footer: {
    line: 'Keep what’s worth keeping, with its source, in one local library.',
    library: 'Try the library',
    github: 'GitHub',
    privacy: 'Privacy',
    terms: 'Terms',
    copyright: '© {year} AnnHub',
    navLabel: 'Site links',
  },
  ui: {
    types: { clip: 'Clip', screenshot: 'Screenshot', highlight: 'Highlight' },
    menu: {
      clip: 'Clip',
      screenshot: 'Screenshot',
      clipHint: 'Save the selection to read and highlight later',
      screenshotHint: 'Drag an area or click an element · save as image',
    },
    toast: { clipped: 'Clipped', undo: 'Undo', edit: 'Edit', undone: 'Undone' },
    edit: { title: 'Title', tags: 'Tags', note: 'Note', more: 'More properties', done: 'Done', addTag: 'Add a tag…', autosave: 'Saved on blur' },
    block: { clip: 'Clip', shot: 'Shot', parent: 'Parent', more: 'More', clipped: 'Clipped' },
    shot: {
      hint: 'Drag to select an area, click to pick an element · Esc to cancel',
      anonymousOn: 'Anonymize: on · 2 areas masked',
      rect: 'Rectangle',
      ellipse: 'Ellipse',
      arrow: 'Arrow',
      pen: 'Pen',
      mosaic: 'Mosaic',
      text: 'Text',
      undo: 'Undo',
      copy: 'Copy',
      download: 'Download',
      cancel: 'Cancel',
      confirm: 'Confirm',
      annotation: 'Retry amplification',
      figure: 'Figure',
    },
    nav: {
      library: 'Library',
      manage: 'Manage',
      all: 'All',
      clips: 'Clips',
      highlights: 'Highlights',
      screenshots: 'Screenshots',
      properties: 'Properties',
      settings: 'Settings',
      export: 'Export content',
      storage: 'Local storage',
      shortcut: 'Screenshot',
      collapse: 'Collapse navigation',
    },
    list: {
      search: 'Search entries…',
      count: '{n} entries',
      countOne: '{n} entry',
      highlightCount: '{n} highlights',
      highlightCountOne: '{n} highlight',
      type: 'Type',
      source: 'Source',
      tags: 'Tags',
      time: 'Time',
      property: 'Property',
      clear: 'Clear filters',
      open: 'Open',
    },
    reader: {
      back: 'Back',
      source: 'Back to source',
      read: 'Read',
      highlights: 'Highlights',
      properties: 'Properties',
      system: 'System fields · read-only',
      empty: 'No highlights yet — select text in the article',
      original: 'Original text',
      locked: 'Original is read-only · {n} highlights',
      lockedOne: 'Original is read-only · {n} highlight',
      note: 'Note',
      context: 'Context',
      addProperty: 'Add property',
      imageUnsaved: 'Image not saved',
      openOriginal: 'Open original',
      savedLocal: 'Stored on this device only',
      close: 'Close',
      delete: 'Delete',
    },
    props: {
      types: { text: 'Text', list: 'List', number: 'Number', checkbox: 'Checkbox', date: 'Date', datetime: 'Date & time' },
      name: 'Name',
      type: 'Type',
      defaultValue: 'Default value',
      usage: 'Usage',
      presets: 'Presets',
      fixed: 'Fixed',
      builtin: 'Built-in',
      empty: 'Empty',
      checked: 'Reviewed',
      unchecked: 'Not reviewed',
    },
    colors: { yellow: 'Yellow', green: 'Green', blue: 'Blue', pink: 'Pink', purple: 'Purple' },
    export: {
      title: 'Export content',
      ready: 'Pack {entries} entries and {images} saved images into one ZIP to read in other tools.',
      includes: 'Included',
      includesBody: 'Markdown for clips and screenshots (properties as frontmatter, highlights as ==…==), plus the processed image bytes.',
      excludes: 'Not included',
      excludesBody: 'Uncommitted edits and interface preferences. It cannot restore the AnnHub database.',
      cancel: 'Cancel',
      action: 'Export ZIP',
      progress: 'Reading committed records and images. Nothing is uploaded anywhere.',
      writing: 'Writing Markdown and images',
      done: 'Export complete',
      doneBody: '{entries} entries and {images} images were written to AnnHub-export.zip.',
      note: 'README.md records when it was exported, what it covers and how many. The ZIP is for reading in other tools; it is not a backup of the AnnHub database.',
      ok: 'Done',
    },
    file: { folder: 'AnnHub-export' },
  },
}
