import type { LandingCopy } from './types'

// 中文文案。内容以 docs/v2/website.md 为准；产品术语以 docs/v2/README.md §4 为准；界面里的字符串与扩展的
// utils/ui-text.ts 一致。页面不得自行发明功能、用户数或评价（website.md §12、§14）。
export const zhCN: LandingCopy = {
  locale: 'zh-CN',
  meta: {
    title: 'AnnHub — 把网页里值得留下的内容，存进同一个本地库',
    description: 'AnnHub 是本地优先的浏览器扩展：把剪藏、高亮和截图连同来源存进同一个本地库，用属性分类、随时找回，并导出为 Obsidian 读得懂的 Markdown。',
    ogTitle: 'AnnHub — 本地优先的剪藏、高亮与截图资料库',
    ogDescription: '保存很容易。难的是之后找得回、分得清。',
    updated: '2026-10-09',
  },
  header: {
    nav: [
      { id: 'ways', label: '剪藏与截图' },
      { id: 'story', label: '一周工作流' },
      { id: 'library', label: '资料库' },
      { id: 'local', label: '本地优先' },
      { id: 'faq', label: '常见问题' },
    ],
    language: { label: 'EN', href: '/en', aria: 'Switch to English' },
    cta: '体验资料库',
    home: 'AnnHub 首页',
    skip: '跳到正文',
    navLabel: '页面导航',
  },
  hero: {
    chip: '浏览器扩展 · 本地优先',
    lead: '把网页里值得留下的内容，存进同一个本地库。',
    body: '剪藏、高亮、截图，带着来源和属性，需要时再找回，也能带去 Obsidian。',
    local: '本地优先。',
    audience: '面向高级工程师、架构师与技术负责人',
    cta: '体验资料库',
    secondary: '查看工作流',
    facts: ['断网也能采集与导出', '数据只在浏览器本地', '导出 Markdown，属性即 frontmatter'],
    captions: { page: '网页 · 选中一段', reader: '资料库 · 阅读、高亮与属性', library: '资料库 · 剪藏与截图在同一处' },
    sketch: '界面示意：依据 v2 设计稿绘制，使用示例数据',
  },
  problem: {
    title: '保存很容易。难的是之后找得回、分得清。',
    items: [
      { title: '散落各处', body: '书签、高亮、截图分在不同的工具和文件夹里。', evidence: ['书签栏', '高亮插件', '截图文件夹'] },
      { title: '脱离来源', body: '只剩一段文字或一张图，不知道出自哪一页、在页面的哪里。', evidence: ['“Without a budget, every client retries at once.”', '出自哪一页？'] },
      { title: '难以归类', body: '没有统一的标签和属性，找回只能靠记忆。', evidence: ['Screenshot 2026-09-14 10.40.png', '重试笔记（最终版）v2.md', '新建文档 (3)'] },
    ],
  },
  ways: {
    title: '两种方式留下内容，在库里读成自己的',
    kinds: [
      { id: 'clip', name: '剪藏', body: '选中一段，或指一下整篇文章、整条推文，一次点击存下来。', caption: '选区菜单，以及指在整块内容上出现的剪藏胶囊' },
      { id: 'screenshot', name: '截图', body: '框选或点选，原位标注，遮住身份信息。', caption: '截图选区里的标注与工具栏' },
      { id: 'highlight', name: '高亮', body: '回到资料库里读剪藏，选中重点、写下想法；不改动原网页。', caption: '在资料库里选中文字，点一种颜色划高亮' },
    ],
    unified: { lead: '它们在同一个库里，用同一套属性分类、一起检索，导出为带 `frontmatter` 的 Markdown，高亮写成 `==…==`。' },
  },
  story: {
    title: '从一篇技术文章，到一份带属性的 Markdown',
    intro: '以一份“支付系统失败重试策略”的设计文档为例：周一读文章、留下内容，周二在库里整理，周四写文档时找回，周五带走。',
    steps: [
      {
        id: 'select',
        when: '周一 10:12',
        title: '选中一段，点“剪藏”',
        body: '一次点击保存，不开窗口。约 3 秒内可以撤销，也能直接补上标签和备注。',
        caption: '文章里选中一段，选区上方出现“剪藏 / 截图”两项菜单',
      },
      {
        id: 'block',
        when: '周一 10:20',
        title: '指一下整节，点“剪藏”',
        body: '不用先选中：指针停在“指数退避加抖动”这一节上，旁边出现胶囊。整节存成 Markdown，保留标题、列表和链接，网页上不留任何记号。',
        caption: '指针停在一节内容上，出现描边和剪藏胶囊',
      },
      {
        id: 'shot',
        when: '周一 10:40',
        title: '框选延迟曲线，截图',
        body: '框选或点选，在选区里直接标注、遮住身份信息。确认后入库；也可以复制出去贴进设计文档，入库的那份保持原样。',
        caption: '截图选区内的原位标注：遮住头像与名字，圈出峰值',
      },
      {
        id: 'read',
        when: '周二 19:20',
        title: '回到资料库，读一遍，划出重点',
        body: '打开剪藏，选中“随机因子”，点一种颜色，写下备注。高亮只存在于库里；再给它加上标签和 project 属性。',
        caption: '资料库的阅读视图：正文里的高亮，右栏是这条条目的属性',
      },
      {
        id: 'find',
        when: '周四 19:20',
        title: '搜索，按属性筛选，回到来源',
        body: '搜“幂等键”，再按 project = 支付重试筛选；筛选条件写进地址栏，刷新后仍在。点“回到来源”核对原文。',
        caption: '资料库里的搜索与属性筛选结果',
      },
      {
        id: 'export',
        when: '周五',
        title: '导出 Markdown，带进 Obsidian',
        body: '每条条目一份 Markdown：属性就是 frontmatter，高亮写成 `==…==`，图片只存一份。放进 Obsidian 的库就能用。',
        caption: '导出的 Markdown 文件：frontmatter 里是属性，正文里的高亮写成 ==…==',
      },
    ],
    stepOf: '{n} / {total}',
    prev: '上一步',
    next: '下一步',
    outro: '断网时，采集、阅读、检索和导出都照常可用。',
  },
  tour: {
    title: '在资料库里读、整理、找回',
    intro: '所有扩展页面都是左侧导航 + 右侧内容。窗口再窄，导航也只折叠为图标栏，不会换成顶栏。',
    hint: '试试看：点左边的导航，点一条条目，再点“阅读”，在正文里选中文字划高亮；用键盘选中后按 H 也可以。',
    pins: [
      { title: '左导航 + 右内容', body: '全部、剪藏、高亮、截图、属性、设置，所有页面共用同一套壳。' },
      { title: '每条条目带着来源', body: '类型、标题、来源主机、时间、标签和属性都在行里；剪藏有高亮时显示高亮数。' },
      { title: '高亮按剪藏分组', body: '划过的重点集中在“高亮”视图，带着颜色和备注；点一条回到阅读视图里的原位置。' },
      { title: '属性小而明确', body: '属性有类型，同名同类型；在条目详情里添加，在属性页里管理，导出时就是 frontmatter。' },
      { title: '一个导出命令', body: '“导出内容”把条目和已保存的图片打成一个 ZIP，供其他工具阅读。' },
    ],
    sketch: '界面示意：依据 v2 设计稿绘制，数据为示例',
  },
  diff: {
    title: '几个明确的取舍',
    items: [
      { visual: 'entry', title: '不是又一个收藏夹', body: '剪藏与截图是同一种条目，都带来源，按类型与属性整理。高亮是读剪藏时划出的重点，留在库里，不改网页。' },
      { visual: 'obsidian', title: '不依赖笔记软件', body: '不装 Obsidian 也有完整的库；装了，导出的 Markdown 直接可用。' },
      { visual: 'properties', title: '属性小而明确', body: '有类型，同名同类型，长文字写在备注里。' },
      { visual: 'offline', title: '本地优先且可阅读', body: '核心链路离线可用；内容和已保存图片可导出为 Markdown ZIP。' },
    ],
    offline: { label: '已断开网络', steps: ['采集', '阅读与高亮', '检索与筛选', '导出 Markdown'] },
    flow: { library: '浏览器里的资料库', zip: 'Markdown + 原图 ZIP', tool: 'Obsidian，或任何读 Markdown 的工具' },
  },
  trust: {
    eyebrow: '本地优先',
    title: '你的材料，不应该成为使用工具的代价',
    body: '扩展把一切留在浏览器本地：条目与图片在 IndexedDB，设置与本地指标在 `chrome.storage`。没有账号，没有 AnnHub 服务器，也没有 AI 服务。',
    items: [
      { title: '断网照常用', body: '采集、阅读、检索、整理和导出都不依赖网络。' },
      { title: '不默认上传', body: '正文、URL、标题和你整理的内容不会发往 AnnHub 或任何第三方。' },
      { title: '只读你指认的内容', body: '只在你选中文字、指一下整块或框选截图时读取页面，不读取你没有指认的内容。' },
      { title: '带得走', body: '导出 Markdown 和已保存的原图（一个 ZIP），属性是 frontmatter。ZIP 供其他工具阅读，不是 AnnHub 数据库的备份。' },
    ],
    exception: {
      title: '唯一的出站请求',
      body: '截图时，扩展后台会代取页面里引用的那张跨域图片，才能把原图存下来：不带凭据，只接受公网地址。剪藏里的图片只保留原地址，阅读时不联网加载。',
    },
    link: '阅读隐私政策',
    diagram: {
      browser: '你的浏览器',
      entries: 'IndexedDB · 条目与图片',
      settings: 'chrome.storage · 设置与本地指标',
      server: 'AnnHub 服务器',
      none: '没有',
      fetch: '截图时代取页面里的图片',
      page: '你正在读的网页',
    },
  },
  faq: {
    title: '常见问题',
    lead: '几个重要的边界。',
    items: [
      {
        q: 'AnnHub 和 Obsidian Web Clipper 有什么区别？',
        a: 'Obsidian Web Clipper 把网页存成 Obsidian 库里的笔记，用模板和属性整理，免费且开源。AnnHub 把剪藏、截图放进浏览器里一个独立的本地库，并能在库里读剪藏、划高亮，不需要 Obsidian 也能阅读、检索和整理，也能把带属性与 `==高亮==` 的 Markdown 导出给它。',
        note: '关于 Obsidian Web Clipper 的描述核对于 2026-10-07，取自 Obsidian 官方帮助文档。',
      },
      {
        q: 'AnnHub 和 Readwise 有什么区别？',
        a: 'Readwise 是云端的阅读与高亮服务；AnnHub 的数据留在浏览器本地，覆盖剪藏、截图与库内高亮，按类型与属性检索。',
        note: '关于 Readwise 的描述核对于 2026-10-03，取自其官方页面。',
      },
      { q: '必须使用 Obsidian 吗？', a: '不需要。库在浏览器里就能用；导出的 Markdown 只是让你需要时能带走。' },
      { q: '数据保存在哪里？', a: '浏览器的本地存储里，不会上传到任何 AnnHub 服务器。' },
      { q: '为什么没有手机端？', a: 'AnnHub 围绕桌面浏览器里的采集、阅读和整理设计，目前没有手机端。' },
      {
        q: '能导出吗？',
        a: '可以。在扩展里点“导出内容”，下载由 Markdown 与已保存图片组成的 ZIP，属性写成 frontmatter。它适合其他工具阅读，不是可以恢复 AnnHub 数据库的备份。',
      },
    ],
  },
  closing: {
    title: '留下的内容，之后还找得到。',
    body: '剪藏与截图带着来源进入同一个本地库。在库里阅读、高亮、按属性找回，需要时再导出为 Markdown。',
    primary: '体验资料库',
    secondary: '查看工作流',
  },
  footer: {
    line: '把值得留下的内容，连同来源一起存进同一个本地库。',
    library: '体验资料库',
    github: 'GitHub',
    privacy: '隐私政策',
    terms: '服务条款',
    copyright: '© {year} AnnHub',
    navLabel: '站点链接',
  },
  ui: {
    types: { clip: '剪藏', screenshot: '截图', highlight: '高亮' },
    menu: { clip: '剪藏', screenshot: '截图', clipHint: '保存选中的内容，之后在资料库里读和高亮', screenshotHint: '框选区域或单击元素 · 保存为图片' },
    toast: { clipped: '已剪藏', undo: '撤销', edit: '编辑', undone: '已撤销' },
    edit: { title: '标题', tags: '标签', note: '备注', more: '更多属性', done: '完成', addTag: '添加标签…', autosave: '失焦即保存' },
    block: { clip: '剪藏', shot: '截图', parent: '上一级', more: '更多', clipped: '已剪藏' },
    shot: {
      hint: '拖拽选择区域，单击选择元素 · Esc 取消',
      anonymousOn: '匿名 开 · 已遮挡 2 处',
      rect: '矩形',
      ellipse: '椭圆',
      arrow: '箭头',
      pen: '画笔',
      mosaic: '马赛克',
      text: '文字',
      undo: '撤销',
      copy: '复制',
      download: '下载',
      cancel: '取消',
      confirm: '确认',
      annotation: '重试放大',
      figure: '图',
    },
    nav: {
      library: '资料库',
      manage: '管理',
      all: '全部',
      clips: '剪藏',
      highlights: '高亮',
      screenshots: '截图',
      properties: '属性',
      settings: '设置',
      export: '导出内容',
      storage: '本地存储',
      shortcut: '截图',
      collapse: '折叠导航',
    },
    list: {
      search: '搜索条目…',
      count: '共 {n} 条',
      countOne: '共 {n} 条',
      highlightCount: '{n} 高亮',
      highlightCountOne: '{n} 高亮',
      type: '类型',
      source: '来源',
      tags: '标签',
      time: '时间',
      property: '属性',
      clear: '清除筛选',
      open: '打开',
    },
    reader: {
      back: '返回',
      source: '回到来源',
      read: '阅读',
      highlights: '高亮',
      properties: '属性',
      system: '系统字段 · 只读',
      empty: '还没有高亮：在正文里选中文字即可',
      original: '原文',
      locked: '原文只读 · {n} 条高亮',
      lockedOne: '原文只读 · {n} 条高亮',
      note: '备注',
      context: '语境',
      addProperty: '添加属性',
      imageUnsaved: '图片未保存',
      openOriginal: '打开原图',
      savedLocal: '只保存在本机',
      close: '关闭',
      delete: '删除',
    },
    props: {
      types: { text: '文本', list: '列表', number: '数字', checkbox: '复选框', date: '日期', datetime: '日期时间' },
      name: '名称',
      type: '类型',
      defaultValue: '默认值',
      usage: '使用数',
      presets: '预设',
      fixed: '固定',
      builtin: '内置',
      empty: '空',
      checked: '已读',
      unchecked: '未读',
    },
    colors: { yellow: '黄色', green: '绿色', blue: '蓝色', pink: '粉色', purple: '紫色' },
    export: {
      title: '导出内容',
      ready: '把 {entries} 条条目与 {images} 张已保存的图片打包为一个 ZIP，用其他工具阅读。',
      includes: '包含',
      includesBody: '剪藏与截图的 Markdown（属性写成 frontmatter，高亮写成 ==…==），以及处理后的图片原字节。',
      excludes: '不包含',
      excludesBody: '尚未提交的编辑、界面偏好。不能用来恢复 AnnHub 的数据库。',
      cancel: '取消',
      action: '导出 ZIP',
      progress: '正在读取已提交的记录与图片，不会上传到任何地方。',
      writing: '写入 Markdown 与图片',
      done: '导出完成',
      doneBody: '{entries} 条条目、{images} 张图片，已写入 AnnHub-export.zip。',
      note: 'README.md 记录了导出时间、范围与数量。这个 ZIP 供其他工具阅读，不是 AnnHub 数据库的备份。',
      ok: '完成',
    },
    file: { folder: 'AnnHub-export' },
  },
}
