/**
 * The single user-facing export: Markdown + saved image ZIP — docs/v2/storage.md §6.
 *
 * Readable by tools like Obsidian; NOT a lossless AnnHub database restore.
 * Environment-neutral: the host passes entries + an asset reader; this
 * module derives the file set, YAML frontmatter (via a serializer, never
 * hand-built), relative image links and the missing-asset manifest. Section
 * headings follow the interface language the export was started in; keys,
 * frontmatter fields and paths never change with it.
 */
import { markdownToPlainText, writeHighlightMarks } from './markdown'
import { BUILTIN_PROPERTY_DEFINITIONS, propertyStorageKey } from './properties'
import { buildZip, type ZipEntry } from './zip'
import type { EntryRecord, ImageAsset, PropertyDefinition, PropertyValue } from './types'

export type ExportLanguage = 'zh' | 'en'

export interface ExportAsset {
  metadata: ImageAsset
  bytes: Uint8Array
}

export interface ExportInput {
  exportedAt: number
  lang: ExportLanguage
  entries: EntryRecord[]
  registry: PropertyDefinition[]
  /** Reads one saved asset; `undefined` marks it missing (partial export). */
  readAsset: (assetId: string) => Promise<ExportAsset | undefined>
}

export interface ExportSummary {
  result: 'full' | 'partial'
  clips: number
  screenshots: number
  missingAssets: string[]
  blob: Blob
}

const LABELS: Record<ExportLanguage, Record<string, string>> = {
  zh: {
    original: '原文',
    context: '语境',
    highlightNotes: '高亮备注',
    note: '备注',
    image: '图片',
    imageMissing: '图片缺失',
    readmeTitle: '导出说明',
    exportedAt: '导出时间',
    counts: '数量',
    missing: '缺失图片',
    notARestore: '本 ZIP 供其他工具阅读，不能用于恢复 AnnHub 数据库。',
  },
  en: {
    original: 'Original text',
    context: 'Context',
    highlightNotes: 'Highlight notes',
    note: 'Note',
    image: 'Image',
    imageMissing: 'Image missing',
    readmeTitle: 'Export notes',
    exportedAt: 'Exported at',
    counts: 'Count',
    missing: 'Missing images',
    notARestore: 'This ZIP is for reading in other tools; it is not an AnnHub database restore.',
  },
}

// ── YAML frontmatter (storage.md §6, entry.md §5.5) ─────────────────────

function yamlScalar(value: Exclude<PropertyValue, unknown[]>): string {
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  // single-quoted string with '' escapes; generated by the serializer only
  return `'${value.replace(/'/g, "''")}'`
}

/** Plain YAML scalar when safe (matches the doc example's list items), quoted otherwise. */
function yamlPlain(item: string): string {
  const needsQuotes =
    /^(?:true|false|null|~|-?\d[\d_.]*(?:[eE][+-]?\d+)?)$/u.test(item) || // would parse as another type
    /^\s|[\s]$/.test(item) ||
    /^[-?:,[\]{}#&*!|>'"%@`]/.test(item) ||
    /:\s|\s#/.test(item) ||
    item.includes('\n')
  return needsQuotes ? `'${item.replace(/'/g, "''")}'` : item
}

function yamlValue(value: PropertyValue, indent = '  '): string {
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    return '\n' + value.map(item => `${indent}- ${yamlPlain(String(item))}`).join('\n')
  }
  return ' ' + yamlScalar(value)
}

function localDate(epochMs: number): string {
  const d = new Date(epochMs)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

function localDateTime(epochMs: number): string {
  const d = new Date(epochMs)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${localDate(epochMs)}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
}

/**
 * Key order (storage.md §6): annhub_id, annhub_type, title, source,
 * created, then remaining built-ins, then custom properties by name.
 * System scalars follow the doc's example: id/title/source quoted, type and
 * created bare; property values serialize per their type.
 */
export function frontmatterFor(entry: EntryRecord, registry: PropertyDefinition[]): string {
  const byKey = new Map(registry.map(def => [propertyStorageKey(def.name), def] as const))
  const lines: string[] = []
  const emitRaw = (key: string, rendered: string | undefined) => {
    if (rendered !== undefined) lines.push(`${key}: ${rendered}`)
  }
  const emit = (key: string, value: PropertyValue | undefined, typeHint?: 'text' | 'date' | 'datetime') => {
    if (value === undefined || value === '' || (Array.isArray(value) && value.length === 0)) return
    if (typeHint === 'date' || typeHint === 'datetime') {
      // dates keep their entry.md §5.2 format, unquoted (storage.md §6)
      lines.push(`${key}: ${value}`)
      return
    }
    lines.push(`${key}:${yamlValue(value)}`)
  }

  emitRaw('annhub_id', entry.id ? `'${entry.id.replace(/'/g, "''")}'` : undefined)
  emitRaw('annhub_type', entry.type)
  emit('title', entry.properties['title'], 'text')
  emitRaw('source', `'${entry.sourceUrl.replace(/'/g, "''")}'`)
  emitRaw('created', localDate(entry.createdAt))
  for (const builtin of BUILTIN_PROPERTY_DEFINITIONS) {
    if (builtin.name === 'title') continue
    emit(builtin.name, entry.properties[builtin.name], builtin.type === 'date' ? 'date' : builtin.type === 'datetime' ? 'datetime' : builtin.type === 'text' ? 'text' : undefined)
  }
  const customNames = Object.keys(entry.properties)
    .filter(name => !BUILTIN_PROPERTY_DEFINITIONS.some(b => propertyStorageKey(b.name) === propertyStorageKey(name)))
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))
  for (const name of customNames) {
    const def = byKey.get(propertyStorageKey(name))
    if (!def) continue
    emit(name, entry.properties[name], def.type === 'date' ? 'date' : def.type === 'datetime' ? 'datetime' : def.type === 'text' ? 'text' : undefined)
  }
  return `---\n${lines.join('\n')}\n---`
}

// ── Bodies ──────────────────────────────────────────────────────────────

function clipBody(entry: EntryRecord, lang: ExportLanguage): string {
  const t = LABELS[lang]
  const sections: string[] = []
  const highlights = [...(entry.highlights ?? [])].sort((a, b) => a.start - b.start)
  sections.push(`## ${t.original}\n\n${writeHighlightMarks(entry.content, highlights)}`)
  if (entry.context) sections.push(`## ${t.context}\n\n${entry.context}`)
  const noted = highlights.filter(highlight => highlight.note?.trim())
  if (noted.length > 0) {
    const notes = noted.map(highlight => `> ${highlight.quote}\n\n${highlight.note}`).join('\n\n')
    sections.push(`## ${t.highlightNotes}\n\n${notes}`)
  }
  if (entry.note?.trim()) sections.push(`## ${t.note}\n\n${entry.note}`)
  return sections.join('\n\n')
}

function screenshotBody(entry: EntryRecord, assetPresent: boolean, lang: ExportLanguage): string {
  const t = LABELS[lang]
  const title = String(entry.properties['title'] ?? 'screenshot')
  const image = assetPresent ? `![${title.replace(/[[\]]/g, '')}](../assets/${entry.assetId}.png)` : t.imageMissing
  const sections = [`## ${t.image}\n\n${image}`]
  if (entry.note?.trim()) sections.push(`## ${t.note}\n\n${entry.note}`)
  return sections.join('\n\n')
}

function readme(lang: ExportLanguage, exportedAt: number, clips: number, screenshots: number, missing: string[]): string {
  const t = LABELS[lang]
  const lines = [
    `# ${t.readmeTitle}`,
    '',
    `- ${t.exportedAt}: ${localDateTime(exportedAt)}`,
    `- ${t.counts}: ${clips + screenshots} (${clips} clips / ${screenshots} screenshots)`,
    `- Format version: 1`,
    `- ${t.notARestore}`,
  ]
  if (missing.length > 0) {
    lines.push('', `## ${t.missing}`, '')
    for (const assetId of missing) lines.push(`- ${assetId}`)
  }
  return lines.join('\n') + '\n'
}

/** Entry summaries shown while paging large exports. */
export function entrySummary(entry: EntryRecord, maxChars = 140): string {
  const plain = markdownToPlainText(entry.content).replace(/\s+/g, ' ')
  return plain.length > maxChars ? `${plain.slice(0, maxChars)}…` : plain
}

// ── The export itself ───────────────────────────────────────────────────

export async function buildExport(input: ExportInput): Promise<ExportSummary> {
  const { exportedAt, lang, entries, registry, readAsset } = input

  // snapshot ids first; a record that changes while reading is re-read or reported
  const ordered = [...entries].sort((a, b) => b.createdAt - a.createdAt || (a.id < b.id ? -1 : 1))
  const zipEntries: ZipEntry[] = []
  const missingAssets: string[] = []
  let clips = 0
  let screenshots = 0

  for (const entry of ordered) {
    if (entry.type === 'clip') {
      clips++
      zipEntries.push({ name: `clips/${entry.id}.md`, data: new TextEncoder().encode(`${frontmatterFor(entry, registry)}\n\n${clipBody(entry, lang)}\n`) })
      continue
    }
    screenshots++
    // assets are read one Blob at a time (storage.md §6)
    const fresh = await readAsset(entry.assetId!)
    const present = fresh !== undefined
    if (!present) missingAssets.push(entry.assetId!)
    zipEntries.push({
      name: `screenshots/${entry.id}.md`,
      data: new TextEncoder().encode(`${frontmatterFor(entry, registry)}\n\n${screenshotBody(entry, present, lang)}\n`),
    })
    if (present) zipEntries.push({ name: `assets/${fresh.metadata.id}.png`, data: fresh.bytes })
  }

  zipEntries.unshift({ name: 'README.md', data: new TextEncoder().encode(readme(lang, exportedAt, clips, screenshots, missingAssets)) })

  return {
    result: missingAssets.length > 0 ? 'partial' : 'full',
    clips,
    screenshots,
    missingAssets,
    blob: buildZip(zipEntries, exportedAt),
  }
}
