/**
 * The single user-facing export: Markdown + saved image ZIP — docs/v2/storage.md §6.
 *
 * Readable by tools like Obsidian; NOT a lossless AnnHub database restore.
 * Environment-neutral: the host passes entries + an asset reader; this
 * module derives the file set, YAML frontmatter (via a serializer, never
 * hand-built), relative image links and the missing-asset manifest. Section
 * headings follow the interface language the export was started in; keys,
 * frontmatter fields and paths never change with it.
 */
import { writeHighlightMarks } from './markdown'
import { BUILTIN_PROPERTY_DEFINITIONS, propertyStorageKey } from './properties'
import { buildZip, type ZipEntry } from './zip'
import { sha256Hex } from './assets'
import type { EntryRecord, ImageAsset, PropertyDefinition, PropertyValue } from './types'

export type ExportLanguage = 'zh' | 'en'

export interface ExportAsset {
  metadata: ImageAsset
  bytes: Uint8Array | Blob
}

export interface ExportInput {
  exportedAt: number
  lang: ExportLanguage
  entries: EntryRecord[]
  registry: PropertyDefinition[]
  /** Reads one saved asset; `undefined` marks it missing (partial export). */
  readAsset: (assetId: string) => Promise<ExportAsset | undefined>
}

export interface ExportSummary {
  result: 'full' | 'partial'
  clips: number
  screenshots: number
  missingAssets: string[]
  blob: Blob
}

const LABELS: Record<ExportLanguage, Record<string, string>> = {
  zh: {
    original: '原文',
    context: '语境',
    highlightNotes: '高亮备注',
    note: '备注',
    image: '图片',
    imageMissing: '图片缺失',
    readmeTitle: '导出说明',
    exportedAt: '导出时间',
    counts: '数量',
    missing: '缺失图片',
    notARestore: '本 ZIP 供其他工具阅读，不能用于恢复 AnnHub 数据库。',
    clips: '剪藏',
    screenshots: '截图',
    formatVersion: '格式版本',
    includes: '包含：已提交的剪藏、截图条目与已保存的图片字节。',
    excludes: '不包含：未提交的编辑、界面偏好、属性注册表和可重建缓存。',
  },
  en: {
    original: 'Original text',
    context: 'Context',
    highlightNotes: 'Highlight notes',
    note: 'Note',
    image: 'Image',
    imageMissing: 'Image missing',
    readmeTitle: 'Export notes',
    exportedAt: 'Exported at',
    counts: 'Count',
    missing: 'Missing images',
    notARestore: 'This ZIP is for reading in other tools; it is not an AnnHub database restore.',
    clips: 'clips',
    screenshots: 'screenshots',
    formatVersion: 'Format version',
    includes: 'Includes committed clips, screenshots, and saved image bytes.',
    excludes: 'Excludes uncommitted edits, interface settings, the property registry, and rebuildable caches.',
  },
}

// ── YAML frontmatter (storage.md §6, entry.md §5.5) ─────────────────────

function yamlScalar(value: Exclude<PropertyValue, unknown[]>): string {
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  // single-quoted string with '' escapes; generated by the serializer only
  return `'${value.replace(/'/g, "''")}'`
}

/** Plain scalars a YAML parser reads as something other than the string they spell (booleans of either generation, null). */
const YAML_RESERVED_SCALAR = /^(?:true|false|yes|no|on|off|y|n|null|~)$/i

function yamlKey(key: string): string {
  return /^[A-Za-z_][A-Za-z0-9_-]*$/.test(key) && !YAML_RESERVED_SCALAR.test(key) ? key : yamlScalar(key)
}

function yamlValue(value: PropertyValue, indent = '  '): string {
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    return '\n' + value.map(item => `${indent}- ${yamlScalar(String(item))}`).join('\n')
  }
  return ' ' + yamlScalar(value)
}

function localDate(epochMs: number): string {
  const d = new Date(epochMs)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

function localDateTime(epochMs: number): string {
  const d = new Date(epochMs)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${localDate(epochMs)}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
}

/**
 * Key order (storage.md §6): annhub_id, annhub_type, title, source,
 * created, then remaining built-ins, then custom properties by name.
 * System scalars follow the doc's example: id/title/source quoted, type and
 * created bare; property values serialize per their type.
 */
export function frontmatterFor(entry: EntryRecord, registry: PropertyDefinition[]): string {
  const byKey = new Map(registry.map(def => [propertyStorageKey(def.name), def] as const))
  const lines: string[] = []
  const emitRaw = (key: string, rendered: string | undefined) => {
    if (rendered !== undefined) lines.push(`${yamlKey(key)}: ${rendered}`)
  }
  const emit = (key: string, value: PropertyValue | undefined, typeHint?: 'text' | 'date' | 'datetime') => {
    if (value === undefined || value === '' || (Array.isArray(value) && value.length === 0)) return
    if (typeHint === 'date' || typeHint === 'datetime') {
      // dates keep their entry.md §5.2 format, unquoted (storage.md §6)
      lines.push(`${yamlKey(key)}: ${value}`)
      return
    }
    lines.push(`${yamlKey(key)}:${yamlValue(value)}`)
  }

  emitRaw('annhub_id', entry.id ? `'${entry.id.replace(/'/g, "''")}'` : undefined)
  emitRaw('annhub_type', entry.type)
  emit('title', entry.properties['title'], 'text')
  emitRaw('source', `'${entry.sourceUrl.replace(/'/g, "''")}'`)
  emitRaw('created', localDate(entry.createdAt))
  for (const builtin of BUILTIN_PROPERTY_DEFINITIONS) {
    if (builtin.name === 'title') continue
    emit(builtin.name, entry.properties[builtin.name], builtin.type === 'date' ? 'date' : builtin.type === 'datetime' ? 'datetime' : builtin.type === 'text' ? 'text' : undefined)
  }
  const customNames = Object.keys(entry.properties)
    .filter(name => !BUILTIN_PROPERTY_DEFINITIONS.some(b => propertyStorageKey(b.name) === propertyStorageKey(name)))
    .sort((a, b) => {
      const lowerA = a.toLowerCase()
      const lowerB = b.toLowerCase()
      return lowerA < lowerB ? -1 : lowerA > lowerB ? 1 : a < b ? -1 : a > b ? 1 : 0
    })
  for (const name of customNames) {
    const def = byKey.get(propertyStorageKey(name))
    if (!def) continue
    emit(name, entry.properties[name], def.type === 'date' ? 'date' : def.type === 'datetime' ? 'datetime' : def.type === 'text' ? 'text' : undefined)
  }
  return `---\n${lines.join('\n')}\n---`
}

// ── Bodies ──────────────────────────────────────────────────────────────

function clipBody(entry: EntryRecord, lang: ExportLanguage): string {
  const t = LABELS[lang]
  const sections: string[] = []
  const highlights = [...(entry.highlights ?? [])].sort((a, b) => a.start - b.start)
  sections.push(writeHighlightMarks(entry.content, highlights))
  if (entry.context) sections.push(`## ${t.context}\n\n${entry.context}`)
  const noted = highlights.filter(highlight => highlight.note?.trim())
  if (noted.length > 0) {
    const notes = noted
      .map(
        highlight =>
          `${highlight.quote
            .split(/\r?\n/)
            .map(line => `> ${line}`)
            .join('\n')}\n\n${highlight.note}`,
      )
      .join('\n\n')
    sections.push(`## ${t.highlightNotes}\n\n${notes}`)
  }
  if (entry.note?.trim()) sections.push(`## ${t.note}\n\n${entry.note}`)
  return sections.join('\n\n')
}

function screenshotBody(entry: EntryRecord, assetPresent: boolean, lang: ExportLanguage): string {
  const t = LABELS[lang]
  const title = String(entry.properties['title'] ?? 'screenshot')
  const image = assetPresent ? `![${title.replace(/[[\]]/g, '')}](../assets/${entry.assetId}.png)` : t.imageMissing
  const sections = [`## ${t.image}\n\n${image}`]
  if (entry.note?.trim()) sections.push(`## ${t.note}\n\n${entry.note}`)
  return sections.join('\n\n')
}

function readme(lang: ExportLanguage, exportedAt: number, clips: number, screenshots: number, missing: string[]): string {
  const t = LABELS[lang]
  const lines = [
    `# ${t.readmeTitle}`,
    '',
    `- ${t.exportedAt}: ${localDateTime(exportedAt)}`,
    `- ${t.counts}: ${clips + screenshots} (${clips} ${t.clips} / ${screenshots} ${t.screenshots})`,
    `- ${t.formatVersion}: 1`,
    `- ${t.includes}`,
    `- ${t.excludes}`,
    `- ${t.notARestore}`,
  ]
  if (missing.length > 0) {
    lines.push('', `## ${t.missing}`, '')
    for (const assetId of missing) lines.push(`- ${assetId}`)
  }
  return lines.join('\n') + '\n'
}

// ── The export itself ───────────────────────────────────────────────────

export async function buildExport(input: ExportInput): Promise<ExportSummary> {
  const { exportedAt, lang, entries, registry, readAsset } = input

  // snapshot ids first; a record that changes while reading is re-read or reported
  const ordered = [...entries].sort((a, b) => b.createdAt - a.createdAt || (a.id < b.id ? -1 : 1))
  const zipEntries: ZipEntry[] = []
  const missingAssets: string[] = []
  let clips = 0
  let screenshots = 0

  for (const entry of ordered) {
    if (entry.type === 'clip') {
      clips++
      zipEntries.push({ name: `clips/${entry.id}.md`, data: new TextEncoder().encode(`${frontmatterFor(entry, registry)}\n\n${clipBody(entry, lang)}\n`) })
      continue
    }
    screenshots++
    // assets are read one Blob at a time (storage.md §6)
    const fresh = await readAsset(entry.assetId!)
    const bytes = fresh?.bytes instanceof Blob ? new Uint8Array(await fresh.bytes.arrayBuffer()) : fresh?.bytes
    const present = Boolean(
      fresh && bytes && fresh.metadata.id === entry.assetId && fresh.metadata.byteLength === bytes.length && fresh.metadata.sha256 === (await sha256Hex(bytes)),
    )
    if (!present) missingAssets.push(entry.assetId!)
    zipEntries.push({
      name: `screenshots/${entry.id}.md`,
      data: new TextEncoder().encode(`${frontmatterFor(entry, registry)}\n\n${screenshotBody(entry, present, lang)}\n`),
    })
    if (present && fresh) zipEntries.push({ name: `assets/${fresh.metadata.id}.png`, data: fresh.bytes })
  }

  zipEntries.unshift({ name: 'README.md', data: new TextEncoder().encode(readme(lang, exportedAt, clips, screenshots, missingAssets)) })

  return {
    result: missingAssets.length > 0 ? 'partial' : 'full',
    clips,
    screenshots,
    missingAssets,
    blob: await buildZip(zipEntries, exportedAt),
  }
}
