/**
 * The single user-facing export: Markdown + saved image ZIP (docs/v2/storage.md §7).
 *
 * Readable by tools like Obsidian; NOT a lossless AnnHub database restore.
 * Environment-neutral: the host passes records + an asset reader; this module
 * derives the file set, YAML frontmatter (via serializer, never hand-built),
 * relative image links and the missing-asset manifest.
 */
import type { FragmentRecord, ImageAsset, ScreenshotRecord } from './types'
import { buildZip, type ZipEntry } from './zip'

export interface ExportHighlight {
  id: string
  text: string
  note?: string
  sourceUrl: string
  sourceTitle?: string
  createdAt: number
}

export interface ExportClip {
  id: string
  text: string
  sourceUrl: string
  sourceTitle?: string
  createdAt: number
}

export interface ExportInput {
  exportedAt: number
  fragments: FragmentRecord[]
  highlights: ExportHighlight[]
  clips: ExportClip[]
  screenshots: ScreenshotRecord[]
  getAsset: (assetId: string) => Promise<{ metadata: ImageAsset; bytes: Blob } | undefined>
}

export interface ExportManifest {
  exportedAt: number
  formatVersion: 'annhub-markdown-zip-1'
  counts: { fragments: number; highlights: number; clips: number; screenshots: number; assets: number }
  /** Assets referenced but not found locally — the UI must show 部分导出. */
  missingAssets: string[]
  partial: boolean
}

const SAFE_ID = /^[A-Za-z0-9_-]+$/

const REVIEW_STATE_LABELS: Record<FragmentRecord['review']['state'], string> = {
  new: '新建',
  learning: '学习中',
  review: '复习中',
  relearning: '重新学习',
}
const MIME_EXT: Record<ImageAsset['mimeType'], string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
}

/** Extension per saved asset id; an id absent here is a missing image (no dead link is written). */
interface AssetLinks {
  ext: Map<string, string>
}

const iso = (epochMs: number): string => new Date(epochMs).toISOString()

function yamlString(value: string): string {
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ')
  return `"${escaped}"`
}

/** YAML frontmatter generated by a serializer — never hand-concatenated (storage.md §7). */
export function yamlFrontmatter(fields: Array<[string, string | string[] | number | boolean]>): string {
  const lines = ['---']
  for (const [key, value] of fields) {
    if (Array.isArray(value)) {
      lines.push(`${key}: [${value.map(v => (typeof v === 'number' ? v : yamlString(v))).join(', ')}]`)
    } else if (typeof value === 'number' || typeof value === 'boolean') {
      lines.push(`${key}: ${value}`)
    } else {
      lines.push(`${key}: ${yamlString(value)}`)
    }
  }
  lines.push('---')
  return lines.join('\n')
}

function fragmentBody(f: FragmentRecord, assets: AssetLinks): string {
  const sections: string[] = []
  sections.push(`# ${f.content}`)

  sections.push('## 页面语境')
  sections.push(f.context.excerpt)
  if (f.context.sourceTitle) sections.push(`> 来源：${f.context.sourceTitle}（${f.context.sourceHost}）`)

  sections.push('## 理解')
  sections.push(f.processing.guess?.trim() || '（未填写）')

  sections.push('## 核验')
  const v = f.processing.verified
  const parts: string[] = [`已确认（来源：${v.source}，${iso(v.confirmedAt)}）`]
  if (v.summary) parts.push(`摘要：${v.summary}`)
  if (v.notes) parts.push(`备注：${v.notes}`)
  sections.push(parts.join('\n'))

  sections.push('## 应用')
  sections.push(f.processing.use)

  if (f.kind === 'visual') {
    const ids = (f.detail as { attachmentIds: string[] }).attachmentIds
    sections.push('## 截图')
    sections.push(ids.map(id => (assets.ext.has(id) ? `![截图](../assets/${id}.${assets.ext.get(id)})` : `图片缺失（资产 ${id} 不在本地库中）`)).join('\n'))
  }
  const r = f.review
  if (r.lastReviewedAt !== undefined) {
    sections.push('## 复习摘要')
    sections.push(
      [
        `状态：${REVIEW_STATE_LABELS[r.state]}（复习 ${r.repetitions} 次，遗忘 ${r.lapses} 次）`,
        `最近复习：${iso(r.lastReviewedAt)}`,
        `下次复习：${iso(r.nextReviewAt)}（间隔 ${r.intervalDays} 天）`,
      ].join('\n'),
    )
  }
  if (f.tags.length) sections.push(`标签：${f.tags.join('、')}`)
  return sections.join('\n\n')
}

function fragmentMarkdown(f: FragmentRecord, assets: AssetLinks): string {
  const fields: Array<[string, string | string[] | number]> = [
    ['annhub_id', f.id],
    ['kind', f.kind],
    ['capture_revision', f.captureRevision],
    ['source_url', f.context.sourceUrl],
    ['captured_at', iso(f.context.capturedAt)],
  ]
  if (f.context.sourceTitle) fields.push(['source_title', f.context.sourceTitle])
  if (f.tags.length) fields.push(['tags', f.tags])
  if (f.kind === 'visual') fields.push(['asset_ids', (f.detail as { attachmentIds: string[] }).attachmentIds])
  return `${yamlFrontmatter(fields)}\n\n${fragmentBody(f, assets)}\n`
}

function highlightMarkdown(h: ExportHighlight): string {
  const fields: Array<[string, string | number]> = [
    ['annhub_id', h.id],
    ['kind', 'highlight'],
    ['source_url', h.sourceUrl],
    ['created_at', iso(h.createdAt)],
  ]
  if (h.sourceTitle) fields.push(['source_title', h.sourceTitle])
  const body = [`# 高亮\n\n${h.text}`]
  if (h.note) body.push(`## 备注\n\n${h.note}`)
  return `${yamlFrontmatter(fields)}\n\n${body.join('\n\n')}\n`
}

function clipMarkdown(c: ExportClip): string {
  const fields: Array<[string, string | number]> = [
    ['annhub_id', c.id],
    ['kind', 'clip'],
    ['source_url', c.sourceUrl],
    ['created_at', iso(c.createdAt)],
  ]
  if (c.sourceTitle) fields.push(['source_title', c.sourceTitle])
  return `${yamlFrontmatter(fields)}\n\n# 剪藏\n\n${c.text}\n`
}

function screenshotMarkdown(s: ScreenshotRecord, assetPresent: boolean, ext: string): string {
  const fields: Array<[string, string | number]> = [
    ['annhub_id', s.id],
    ['kind', 'screenshot'],
    ['asset_id', s.assetId],
    ['source_url', s.sourceUrl],
    ['captured_at', iso(s.capturedAt)],
  ]
  if (s.sourceTitle) fields.push(['source_title', s.sourceTitle])
  const body = assetPresent ? `![截图](../assets/${s.assetId}.${ext})` : '图片缺失（资产不在本地库中）'
  return `${yamlFrontmatter(fields)}\n\n# 截图\n\n${body}\n`
}

function readmeMarkdown(manifest: ExportManifest): string {
  const lines = [
    '# AnnHub 内容导出',
    '',
    '这是扩展内容的可阅读导出（Markdown + 已保存原图），供 Obsidian 等工具使用。',
    '它不是 AnnHub 数据库的备份，不承诺恢复复习调度、日志或 Desktop 状态。',
    '',
    `- 格式版本：${manifest.formatVersion}`,
    `- 导出时间：${iso(manifest.exportedAt)}`,
    `- Fragment：${manifest.counts.fragments} 条（fragments/）`,
    `- 高亮：${manifest.counts.highlights} 条（highlights/）`,
    `- 剪藏：${manifest.counts.clips} 条（clips/）`,
    `- 截图：${manifest.counts.screenshots} 条（screenshots/）`,
    `- 图片资产：${manifest.counts.assets} 个（assets/）`,
  ]
  if (manifest.partial) {
    lines.push('', `**部分导出**：以下 ${manifest.missingAssets.length} 个图片资产缺失，未写入 ZIP：`, ...manifest.missingAssets.map(id => `- ${id}`))
  }
  lines.push('', '不包含：未提交的表单、Desktop 独有的复习日志、交付队列、Provider 密钥与 UI 偏好。')
  return lines.join('\n') + '\n'
}

/** Blob → bytes with a FileReader fallback (jsdom-era Blobs lack arrayBuffer). */
export async function blobBytes(blob: Blob): Promise<Uint8Array> {
  if (typeof blob.arrayBuffer === 'function') return new Uint8Array(await blob.arrayBuffer())
  return await new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(new Uint8Array(reader.result as ArrayBuffer))
    reader.onerror = () => reject(reader.error ?? new Error('BLOB_READ_FAILED'))
    reader.readAsArrayBuffer(blob)
  })
}

/**
 * Builds the export ZIP. IDs and capture revisions are fixed from the input
 * snapshot; assets are read one by one so large image sets never load as a
 * single Base64 string (storage.md §7).
 */
export async function buildExportZip(input: ExportInput): Promise<{ blob: Blob; manifest: ExportManifest }> {
  const { fragments, highlights, clips, screenshots } = input
  for (const list of [fragments.map(f => f.id), highlights.map(h => h.id), clips.map(c => c.id), screenshots.map(s => s.id)].flat()) {
    if (!SAFE_ID.test(list)) throw new Error(`UNSAFE_ID:${list}`)
  }

  // Referenced assets: visual attachments + screenshot records.
  const referenced = new Set<string>()
  for (const f of fragments) {
    if (f.kind === 'visual') for (const id of (f.detail as { attachmentIds: string[] }).attachmentIds) referenced.add(id)
    if (f.context.locator.type === 'image') referenced.add(f.context.locator.assetId)
  }
  for (const s of screenshots) referenced.add(s.assetId)

  const entries: ZipEntry[] = []
  const missingAssets: string[] = []
  const includedAssets = new Set<string>()
  const assetExt = new Map<string, string>()

  for (const assetId of referenced) {
    const asset = await input.getAsset(assetId)
    if (!asset) {
      missingAssets.push(assetId)
      continue
    }
    const ext = MIME_EXT[asset.metadata.mimeType]
    entries.push({ name: `assets/${assetId}.${ext}`, data: await blobBytes(asset.bytes) })
    includedAssets.add(assetId)
    assetExt.set(assetId, ext)
  }

  const manifest: ExportManifest = {
    exportedAt: input.exportedAt,
    formatVersion: 'annhub-markdown-zip-1',
    counts: {
      fragments: fragments.length,
      highlights: highlights.length,
      clips: clips.length,
      screenshots: screenshots.length,
      assets: includedAssets.size,
    },
    missingAssets,
    partial: missingAssets.length > 0,
  }

  for (const f of fragments) entries.push({ name: `fragments/${f.id}.md`, data: new TextEncoder().encode(fragmentMarkdown(f, { ext: assetExt })) })
  for (const h of highlights) entries.push({ name: `highlights/${h.id}.md`, data: new TextEncoder().encode(highlightMarkdown(h)) })
  for (const c of clips) entries.push({ name: `clips/${c.id}.md`, data: new TextEncoder().encode(clipMarkdown(c)) })
  for (const s of screenshots) {
    entries.push({ name: `screenshots/${s.id}.md`, data: new TextEncoder().encode(screenshotMarkdown(s, includedAssets.has(s.assetId), assetExt.get(s.assetId) ?? 'png')) })
  }
  entries.unshift({ name: 'README.md', data: new TextEncoder().encode(readmeMarkdown(manifest)) })

  // Final sanity check: record counts and attachment references (storage.md §7).
  const expected = 1 + fragments.length + highlights.length + clips.length + screenshots.length + includedAssets.size
  if (entries.length !== expected) {
    throw new Error(`EXPORT_COUNT_MISMATCH:${entries.length}/${expected}`)
  }
  for (const f of fragments) {
    if (f.kind === 'visual') {
      for (const id of (f.detail as { attachmentIds: string[] }).attachmentIds) {
        if (!includedAssets.has(id) && !missingAssets.includes(id)) throw new Error(`ATTACHMENT_UNRESOLVED:${id}`)
      }
    }
  }

  const blob = buildZip(entries, input.exportedAt)
  if (blob.size === 0) throw new Error('EXPORT_EMPTY')
  return { blob, manifest }
}
