import { defineMessages } from './define'

/** Media-clip capture window (extension.md §4; fragments.md `media-clip`). */
export const media = defineMessages({
  'media.title': { zh: '保存媒体片段', en: 'Save media clip' },
  'media.saved': { zh: '✅ 已保存为「媒体片段」', en: '✅ Saved as “Media clip”' },
  'media.target.video': { zh: '视频', en: 'Video' },
  'media.target.audio': { zh: '音频', en: 'Audio' },
  'media.markStart': { zh: '设为起点', en: 'Set start' },
  'media.markEnd': { zh: '设为终点', en: 'Set end' },
  'media.startPlaceholder': { zh: '起(秒)', en: 'Start (s)' },
  'media.endPlaceholder': { zh: '止(秒)', en: 'End (s)' },
  'media.duration': { zh: '时长 {duration}', en: 'Duration {duration}' },
  'media.durationUnknown': { zh: '未知', en: 'unknown' },
  'media.summary.label': { zh: '要点摘要（必填，即这条碎片的核心内容）', en: 'Key points (required — the core content of this Fragment)' },
  'media.summary.placeholder': { zh: '这几十秒讲了什么值得记住的点？', en: 'What is worth remembering in these seconds?' },
  'media.transcript.label': { zh: '转写（手工记录/修正，可选）', en: 'Transcript (typed or corrected by hand, optional)' },
  'media.transcript.placeholder': { zh: '逐句或摘录式转写；后续可修正', en: 'Sentence by sentence or excerpt style; you can fix it later' },
  'media.context.label': { zh: '页面语境（可选）', en: 'Page context (optional)' },
  'media.context.placeholder': { zh: '这段出现在什么讨论里？', en: 'What discussion does this part belong to?' },
  'media.excerptMarker': { zh: '（{range} 转写节选）', en: '({range} transcript excerpt)' },
  'media.verify.title': { zh: '核验 — 回放该时间段并确认转写', en: 'Verify — replay this range and confirm the transcript' },
  'media.verify.replay': { zh: '▶ 回放区间', en: '▶ Replay range' },
  'media.verify.replayed': { zh: '已回放确认', en: 'Confirm after replay' },
  'media.verify.manual': { zh: '手工核对后确认', en: 'Confirm after a manual check' },
  'media.verify.sourceReplay': { zh: '回放原文', en: 'replayed the source' },
  'media.verify.sourceManual': { zh: '手工', en: 'manual' },
  'media.verify.note': { zh: '已确认核对（{source}，{time}）', en: 'Confirmed ({source}, {time})' },
  'media.use.label': { zh: '应用（必填）', en: 'Apply (required)' },
  'media.use.placeholder': { zh: '准备在什么时候用这段内容？', en: 'When do you plan to use this passage?' },
  'media.use.repeatsSummary': { zh: '应用不能只复述摘要', en: '“Apply” cannot just repeat the key points' },
  'media.duplicate': { zh: '已保存过相同内容的媒体片段。仍要保存？', en: 'A media clip with the same content was already saved. Save anyway?' },
  'media.saveFailed': { zh: '保存失败：{error}。输入已保留，可直接重试。', en: 'Save failed: {error}. Your input is kept — you can retry right away.' },
})
