/**
 * Build script: turn a general-corpus word-frequency list into a compact
 * word -> frequency-band map for the vocab "difficulty gate".
 *
 * Source: OpenSubtitles 2018 English 50k frequency list (hermitdave/FrequencyWords),
 *   a free SUBTLEX-equivalent corpus. Format per line: `<word> <count>`.
 *   Placed at scripts/data/opensubtitles-en-50k.txt.
 *
 * Banding: words are bucketed by Zipf value `log10(count / totalTokens * 1e9)`.
 *   band 1 = most frequent (easiest) ... band 7 = least frequent (hardest, still in-table).
 *   Words NOT in the output table never appear in this general corpus and are treated
 *   by the runtime as "do not annotate" (likely proper nouns / jargon / noise).
 *
 * Usage: npx tsx scripts/build-frequency-data.ts
 * Output: entrypoints/content/vocab-label/frequency-band-data.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// Keep all alphabetic words from the 50k frequency list. The list is itself a
// frequency-filtered corpus (words attested above a minimum count), so its tail is
// still genuine low-frequency English vocabulary (e.g. "ubiquitous", "formative").
// True proper nouns / domain jargon (e.g. "kubernetes", "mitochondria") simply never
// appear in this general corpus and therefore resolve to band = null at runtime.
const TOP_N = 50000

// Zipf cut points (high -> low frequency). Index + 1 = band number.
// zipf >= 5.0 -> band 1, [4.5,5.0) -> 2, [4.0,4.5) -> 3, [3.5,4.0) -> 4,
// [3.0,3.5) -> 5, [2.5,3.0) -> 6, < 2.5 -> 7
const ZIPF_CUTS = [5.0, 4.5, 4.0, 3.5, 3.0, 2.5]

function zipfToBand(zipf: number): number {
  for (let i = 0; i < ZIPF_CUTS.length; i++) {
    if (zipf >= ZIPF_CUTS[i]) return i + 1
  }
  return ZIPF_CUTS.length + 1
}

// ── 1. Load raw frequency list ──────────────────────────────────────────────

const srcPath = resolve(__dirname, 'data/opensubtitles-en-50k.txt')
const rawLines = readFileSync(srcPath, 'utf8').trim().split('\n')

interface Row {
  word: string
  count: number
}

const rows: Row[] = []
let totalTokens = 0
for (const line of rawLines) {
  const [word, countStr] = line.trim().split(/\s+/)
  const count = Number(countStr)
  if (!word || !Number.isFinite(count)) continue
  totalTokens += count
  // Keep only lowercase pure-alpha words of length >= 2.
  if (!/^[a-z]+$/.test(word) || word.length < 2) continue
  rows.push({ word, count })
}

console.log(`Loaded ${rawLines.length} lines, total tokens = ${totalTokens}`)

// ── 2. Band assignment for the top-N alpha words ─────────────────────────────

const wordBand = new Map<string, number>()
let kept = 0
for (const { word, count } of rows) {
  if (kept >= TOP_N) break
  kept++
  const zipf = Math.log10((count / totalTokens) * 1e9)
  const band = zipfToBand(zipf)
  // First occurrence wins (rows are already frequency-sorted = lowest band).
  if (!wordBand.has(word)) wordBand.set(word, band)
}

console.log(`Kept ${wordBand.size} unique alpha words (top ${TOP_N})`)

const MAX_BAND = ZIPF_CUTS.length + 1

// ── 3. Distribution stats ────────────────────────────────────────────────────

const dist: Record<number, number> = {}
for (const b of wordBand.values()) dist[b] = (dist[b] || 0) + 1
console.log('Band distribution:', dist)

// ── 4. Generate TypeScript output ─────────────────────────────────────────────

const byBand = new Map<number, string[]>()
for (const [word, band] of wordBand) {
  const list = byBand.get(band) ?? []
  list.push(word)
  byBand.set(band, list)
}
for (const list of byBand.values()) list.sort()

const lines: string[] = []
lines.push(`// Auto-generated by scripts/build-frequency-data.ts — DO NOT EDIT`)
lines.push(`// Source: OpenSubtitles 2018 English 50k frequency list (hermitdave/FrequencyWords)`)
lines.push(`// band 1 = most frequent (easiest) ... band ${MAX_BAND} = least frequent (hardest, in-table)`)
lines.push(`// Words absent from this table are the long tail (rank > ${TOP_N}); the runtime treats them as "do not annotate".`)
lines.push(`// Total: ${wordBand.size} words`)
lines.push(``)
lines.push(`export const MAX_FREQUENCY_BAND = ${MAX_BAND}`)
lines.push(``)
lines.push(`const BAND_WORDS: Record<number, readonly string[]> = {`)
for (let band = 1; band <= MAX_BAND; band++) {
  const words = byBand.get(band) ?? []
  if (words.length === 0) {
    lines.push(`  ${band}: [],`)
    continue
  }
  lines.push(`  ${band}: [`)
  for (let i = 0; i < words.length; i += 10) {
    const chunk = words
      .slice(i, i + 10)
      .map(w => `'${w}'`)
      .join(',')
    lines.push(`    ${chunk},`)
  }
  lines.push(`  ],`)
}
lines.push(`}`)
lines.push(``)
lines.push(`const FREQUENCY_BAND_MAP = new Map<string, number>()`)
lines.push(`for (const [band, words] of Object.entries(BAND_WORDS)) {`)
lines.push(`  const b = Number(band)`)
lines.push(`  for (const w of words) FREQUENCY_BAND_MAP.set(w, b)`)
lines.push(`}`)
lines.push(``)
lines.push(`/** Frequency band 1..${MAX_BAND} (lower = more frequent/easier), or null if not in the top-${TOP_N} general-corpus list. */`)
lines.push(`export function getWordFrequencyBand(word: string): number | null {`)
lines.push(`  return FREQUENCY_BAND_MAP.get(word) ?? null`)
lines.push(`}`)
lines.push(``)
lines.push(`export { FREQUENCY_BAND_MAP }`)
lines.push(``)

const outPath = resolve(ROOT, 'entrypoints/content/vocab-label/frequency-band-data.ts')
writeFileSync(outPath, lines.join('\n'), 'utf8')

console.log(`\nWritten to: ${outPath}`)
console.log(`File size: ${(readFileSync(outPath).length / 1024).toFixed(1)} KB`)
