/**
 * Build script: merge Oxford 5000 + CEFR-J data into a single CEFR word map.
 *
 * Usage: node --import=tsx scripts/build-cefr-data.ts
 *   (or: npx tsx scripts/build-cefr-data.ts)
 *
 * Output: entrypoints/content/vocab-label/cefr-data.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2'

const CEFR_RANK: Record<CEFRLevel, number> = { A1: 1, A2: 2, B1: 3, B2: 4, C1: 5, C2: 6 }
const VALID_LEVELS = new Set<string>(Object.keys(CEFR_RANK))

function isValidCEFR(s: string): s is CEFRLevel {
  return VALID_LEVELS.has(s)
}

function normalizeWord(w: string): string {
  return w.toLowerCase().replace(/[^\w'-]/g, '').trim()
}

// ── 1. Load Oxford 5000 ─────────────────────────────────────────────────────

interface OxfordEntry {
  id: number
  value: { word: string; level: string; type: string }
}

const oxfordPath = resolve(__dirname, 'data/oxford-5000-full.json')
const oxfordRaw: OxfordEntry[] = JSON.parse(readFileSync(oxfordPath, 'utf8'))

const merged = new Map<string, CEFRLevel>()

for (const entry of oxfordRaw) {
  const word = normalizeWord(entry.value.word)
  const level = entry.value.level?.trim()
  if (!word || word.length < 2 || !isValidCEFR(level)) continue

  const existing = merged.get(word)
  // Keep lowest (easiest) level when same word appears with different POS
  if (!existing || CEFR_RANK[level] < CEFR_RANK[existing]) {
    merged.set(word, level)
  }
}

console.log(`Oxford 5000: loaded ${merged.size} unique words`)

// ── 2. Load CEFR-J Vocabulary Profile ───────────────────────────────────────

const cefrjPath = resolve(__dirname, 'data/cefrj-vocabulary-profile.csv')
const cefrjLines = readFileSync(cefrjPath, 'utf8').trim().split('\n').slice(1) // skip header

let cefrjAdded = 0
for (const line of cefrjLines) {
  const cols = line.split(',')
  const raw = cols[0]?.trim() ?? ''
  const level = cols[2]?.trim() ?? ''

  // CEFR-J has compound entries like "a.m./A.M./am/AM" — split on /
  const variants = raw.includes('/') ? raw.split('/') : [raw]

  for (const variant of variants) {
    const word = normalizeWord(variant)
    if (!word || word.length < 2 || !isValidCEFR(level)) continue

    const existing = merged.get(word)
    if (!existing || CEFR_RANK[level as CEFRLevel] < CEFR_RANK[existing]) {
      if (!existing) cefrjAdded++
      merged.set(word, level as CEFRLevel)
    }
  }
}

console.log(`CEFR-J: added ${cefrjAdded} new words (not in Oxford 5000)`)
console.log(`Total merged: ${merged.size} unique words`)

// ── 3. Distribution stats ───────────────────────────────────────────────────

const dist: Record<string, number> = {}
for (const level of merged.values()) {
  dist[level] = (dist[level] || 0) + 1
}
console.log('Level distribution:', dist)

// ── 4. Generate TypeScript output ───────────────────────────────────────────

// Sort entries for deterministic output
const sortedEntries = [...merged.entries()].sort(([a], [b]) => a.localeCompare(b))

const lines: string[] = []
lines.push(`// Auto-generated by scripts/build-cefr-data.ts — DO NOT EDIT`)
lines.push(`// Sources: Oxford 5000 + CEFR-J Vocabulary Profile`)
lines.push(`// Total: ${sortedEntries.length} words`)
lines.push(``)
lines.push(`export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2'`)
lines.push(``)

// Group words by level for more compact output
const byLevel = new Map<CEFRLevel, string[]>()
for (const [word, level] of sortedEntries) {
  const list = byLevel.get(level) ?? []
  list.push(word)
  byLevel.set(level, list)
}

lines.push(`const LEVEL_WORDS: Record<CEFRLevel, readonly string[]> = {`)
for (const level of ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'] as CEFRLevel[]) {
  const words = byLevel.get(level) ?? []
  if (words.length === 0) {
    lines.push(`  ${level}: [],`)
  } else {
    // Write words as a compact array, ~10 words per line
    lines.push(`  ${level}: [`)
    for (let i = 0; i < words.length; i += 10) {
      const chunk = words.slice(i, i + 10).map(w => `'${w.replace(/'/g, "\\'")}'`).join(',')
      lines.push(`    ${chunk},`)
    }
    lines.push(`  ],`)
  }
}
lines.push(`}`)
lines.push(``)
lines.push(`// Build lookup map at module load time`)
lines.push(`const CEFR_WORD_MAP = new Map<string, CEFRLevel>()`)
lines.push(`for (const [level, words] of Object.entries(LEVEL_WORDS) as [CEFRLevel, readonly string[]][]) {`)
lines.push(`  for (const w of words) CEFR_WORD_MAP.set(w, level)`)
lines.push(`}`)
lines.push(``)
lines.push(`export function getCEFRLevel(word: string): CEFRLevel | null {`)
lines.push(`  return CEFR_WORD_MAP.get(word) ?? null`)
lines.push(`}`)
lines.push(``)
lines.push(`export { CEFR_WORD_MAP }`)
lines.push(``)

const outPath = resolve(ROOT, 'entrypoints/content/vocab-label/cefr-data.ts')
writeFileSync(outPath, lines.join('\n'), 'utf8')

console.log(`\nWritten to: ${outPath}`)
console.log(`File size: ${(readFileSync(outPath).length / 1024).toFixed(1)} KB`)
