#!/usr/bin/env bash
# Sync cross-language fixtures: the canonical source is fixtures/interop (generated by the
# TypeScript tests), consumed by the Swift tests. CI runs this and fails on any diff.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p app/Tests/AnnHubCoreTests/Fixtures
cp fixtures/interop/* app/Tests/AnnHubCoreTests/Fixtures/
