// Desktop local hub — R1 per-item delivery protocol (docs/v2/storage.md §8)
// plus the R3 bidirectional endpoints (§9). The HTTP transport is a thin
// Network.framework shim in the Desktop app; ALL protocol logic lives here so
// it is unit-testable without sockets.
//
// Endpoints (Bearer token = the pairing token, generated by Desktop and typed
// into the extension; storage.md §8):
//   GET  /health                  → status/version/apiVersion/deviceId/paired (no auth)
//   POST /v1/pair                 → pairing handshake (validates the token)
//   PUT  /v1/fragments/{id}       → one fragment's capture fields (JSON, no review)
//   PUT  /v1/assets/{id}          → one image's raw bytes (MIME/length/sha in headers)
//   POST /v1/events               → idempotent extension event batch (R3)
//   GET  /v1/changes?cursor&limit → Desktop mutation cursor feed (R3)

import Foundation

public struct HubRequest: Equatable, Sendable {
    public var method: String
    public var path: String
    public var bearerToken: String?
    /// Header names lowercased (e.g. "x-annhub-sha256", "content-type").
    public var headers: [String: String]
    public var body: Data?

    public init(
        method: String,
        path: String,
        bearerToken: String? = nil,
        headers: [String: String] = [:],
        body: Data? = nil
    ) {
        self.method = method
        self.path = path
        self.bearerToken = bearerToken
        self.headers = Dictionary(uniqueKeysWithValues: headers.map { ($0.key.lowercased(), $0.value) })
        self.body = body
    }
}

public struct HubResponse: Equatable, Sendable {
    public var status: Int
    public var contentType: String
    public var body: Data

    public static func json(_ status: Int, _ object: [String: Any]) -> HubResponse {
        let data = (try? JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])) ?? Data("{}".utf8)
        return HubResponse(status: status, contentType: "application/json", body: data)
    }

    public func decode<T: Decodable>(_ type: T.Type) -> T? {
        try? JSONDecoder().decode(T.self, from: body)
    }

    public func errorField() -> String? {
        guard let object = (try? JSONSerialization.jsonObject(with: body)) as? [String: Any] else {
            return nil
        }
        return object["error"] as? String
    }
}

/// Recent per-item delivery outcome ring for the system page (desktop.md §8).
public struct DeliveryOutcome: Codable, Equatable, Sendable {
    public var method: String
    public var path: String
    public var status: Int
    public var at: Int

    public init(method: String, path: String, status: Int, at: Int) {
        self.method = method
        self.path = path
        self.status = status
        self.at = at
    }
}

struct PutFragmentBody: Decodable {
    var deviceId: String
    var fragment: WireValue
}

public final class DesktopHub: @unchecked Sendable {
    public static let apiVersion = "fragment-put-v1"
    public static let hubVersion = 2

    public let store: FragmentStore
    /// Generated by Desktop (never adopted from a client). The Desktop app
    /// persists it and hands the stored value back in on the next launch.
    public private(set) var pairToken: String
    /// Set by a successful /v1/pair; cleared by rotatePairToken().
    public private(set) var lastPairedAt: Int?
    public private(set) var lastConnectionAt: Int?
    /// Last ~50 per-item delivery outcomes (in-memory; the durable facts stay
    /// in SQLite — delivered fragments, assets and missing-attachment count).
    public private(set) var recentDeliveries: [DeliveryOutcome] = []
    /// /v1/events counters for the system page (in-memory).
    public private(set) var eventsStats = EventsStats()
    private let deliveryRingCapacity = 50
    private let lock = NSLock()

    /// `pairToken` restores the persisted code; nil or empty generates a new one.
    public init(store: FragmentStore, pairToken: String? = nil) {
        self.store = store
        if let pairToken, !pairToken.isEmpty {
            self.pairToken = pairToken
        } else {
            self.pairToken = Self.generatePairToken()
        }
    }

    /// 16 characters in four dash-separated groups, drawn from an alphabet
    /// without look-alikes (no 0/O/1/I/L) so it survives being read aloud or
    /// retyped (~79 bits).
    public static func generatePairToken() -> String {
        let alphabet = Array("ABCDEFGHJKMNPQRSTUVWXYZ23456789")
        var rng = SystemRandomNumberGenerator()
        let groups = (0..<4).map { _ in
            String((0..<4).map { _ in alphabet[Int(rng.next() % UInt64(alphabet.count))] })
        }
        return groups.joined(separator: "-")
    }

    /// "Regenerate" on the system page: the old code stops working at once,
    /// local data and pending deliveries stay (desktop.md §6, storage.md §8).
    @discardableResult
    public func rotatePairToken() -> String {
        let token = Self.generatePairToken()
        withLock {
            pairToken = token
            lastPairedAt = nil
        }
        return token
    }

    private func authorized(_ request: HubRequest) -> Bool {
        let token = currentPairToken()
        return request.bearerToken == token && !token.isEmpty
    }

    /// All mutable state below is guarded by `lock`: lastConnectionAt
    /// stamping, the delivery ring, eventsStats, the pair token and
    /// lastPairedAt. The socket layer invokes handle() concurrently per
    /// connection, so an unlocked read-modify-write would race (e.g. a
    /// rotation racing a pair handshake, or a torn lastConnectionAt).
    private func withLock<T>(_ body: () -> T) -> T {
        lock.lock()
        defer { lock.unlock() }
        return body()
    }

    private func currentPairToken() -> String {
        withLock { pairToken }
    }

    private func stamp(_ request: HubRequest, _ response: HubResponse) -> HubResponse {
        let now = Int(Date().timeIntervalSince1970 * 1000)
        withLock {
            // A rejected token is not an extension connection.
            if response.status != 401 { lastConnectionAt = now }
            if request.method == "PUT" {
                recentDeliveries.append(
                    DeliveryOutcome(
                        method: request.method,
                        path: request.path,
                        status: response.status,
                        at: now
                    ))
                if recentDeliveries.count > deliveryRingCapacity {
                    recentDeliveries.removeFirst(recentDeliveries.count - deliveryRingCapacity)
                }
            }
        }
        return response
    }

    /// Pure handler — the socket layer only parses HTTP and forwards this.
    public func handle(_ request: HubRequest) -> HubResponse {
        let response = route(request)
        return stamp(request, response)
    }

    private func route(_ request: HubRequest) -> HubResponse {
        switch (request.method, request.path) {
        case ("GET", "/health"):
            // No auth; only version + availability (storage.md §8).
            let paired = withLock { lastPairedAt != nil }
            return .json(
                200,
                [
                    "status": "ok",
                    "version": Self.hubVersion,
                    "apiVersion": Self.apiVersion,
                    "deviceId": store.deviceId,
                    "paired": paired,
                ])

        case ("POST", "/v1/pair"):
            guard let token = request.bearerToken, !token.isEmpty else {
                return .json(401, ["error": "unauthorized"])
            }
            // The handshake only validates the code Desktop generated; it never
            // adopts a client-supplied one.
            return withLock {
                guard token == pairToken else {
                    return HubResponse.json(401, ["paired": false, "error": "unauthorized"])
                }
                lastPairedAt = Int(Date().timeIntervalSince1970 * 1000)
                return HubResponse.json(200, ["paired": true, "deviceId": store.deviceId])
            }

        case ("PUT", let path) where path.hasPrefix("/v1/fragments/"):
            guard authorized(request) else { return .json(401, ["error": "unauthorized"]) }
            return putFragment(request, urlId: String(path.dropFirst("/v1/fragments/".count)))

        case ("PUT", let path) where path.hasPrefix("/v1/assets/"):
            guard authorized(request) else { return .json(401, ["error": "unauthorized"]) }
            return putAsset(request, urlId: String(path.dropFirst("/v1/assets/".count)))

        case ("POST", "/v1/events"):
            guard authorized(request) else { return .json(401, ["error": "unauthorized"]) }
            return postEvents(request)

        case ("GET", let path) where path.hasPrefix("/v1/changes"):
            guard authorized(request) else { return .json(401, ["error": "unauthorized"]) }
            return getChanges(request)

        default:
            return .json(404, ["error": "not found"])
        }
    }

    // ── PUT /v1/fragments/{id} (storage.md §8) ───────────────────────────

    /// Shared revision/hash delivery outcome — used by PUT and /v1/events.
    enum FragmentDeliveryOutcome: Equatable {
        /// First write; review initialized, device id + hash stored.
        case created(revision: Int, hash: String)
        /// Greater revision applied; capture fields replaced, review kept.
        case applied(revision: Int, hash: String)
        /// Same revision + same hash (idempotent; stale=false) or an older
        /// revision (stale=true — response adds currentRevision).
        case unchanged(stale: Bool, revision: Int, hash: String)
        /// Same revision with a different payload.
        case conflict
        /// Local deletion marker blocks the id (410 for PUT).
        case deleted
    }

    /// The single revision/hash delivery path (PUT and fragment events both
    /// route here): capture fields only, review preserved on updates.
    private func deliverFragment(
        _ record: FragmentRecord, deviceId: String, payloadHash: String
    ) throws -> FragmentDeliveryOutcome {
        // Check-then-write: two deliveries of one id must not both see "first write".
        try store.exclusive {
            try deliverFragmentLocked(record, deviceId: deviceId, payloadHash: payloadHash)
        }
    }

    private func deliverFragmentLocked(
        _ record: FragmentRecord, deviceId: String, payloadHash: String
    ) throws -> FragmentDeliveryOutcome {
        if try store.isDeleted(id: record.id) {
            return .deleted
        }
        guard let delivery = try store.fragmentDelivery(id: record.id) else {
            try store.upsertFragment(record, deviceId: deviceId, payloadHash: payloadHash)
            return .created(revision: record.captureRevision, hash: payloadHash)
        }
        if record.captureRevision < delivery.revision {
            return .unchanged(stale: true, revision: delivery.revision, hash: delivery.payloadHash)
        }
        if record.captureRevision == delivery.revision {
            if payloadHash == delivery.payloadHash {
                return .unchanged(stale: false, revision: delivery.revision, hash: delivery.payloadHash)
            }
            return .conflict
        }
        // Greater revision: replace capture fields ONLY — never review.
        var updated = record
        if let stored = try store.getFragment(id: record.id) {
            updated.review = stored.review
        }
        try store.upsertFragment(updated, deviceId: deviceId, payloadHash: payloadHash)
        return .applied(revision: record.captureRevision, hash: payloadHash)
    }

    enum FragmentDeliveryError: Error {
        case invalid(String)
    }

    /// Parses + validates a wire fragment tree, then routes it through the
    /// shared delivery path. `.invalid` when the body/fragment fails decode
    /// or validation.
    private func parseAndDeliverFragmentTree(
        _ tree: WireValue, deviceId: String
    ) throws -> Result<FragmentDeliveryOutcome, FragmentDeliveryError> {
        guard let fragmentData = try? JSONEncoder.learningCore().encode(tree),
            let record = try? JSONDecoder.learningCore().decode(FragmentRecord.self, from: fragmentData)
        else { return .failure(.invalid("INVALID_BODY")) }
        // Full-record validation with the reconstructed fresh review (the
        // wire never carries review; storage.md §8).
        let validation = validateFragment(record)
        guard validation.ok, validation.code == nil else {
            return .failure(.invalid((validation.code ?? .detailFieldInvalid).rawValue))
        }
        let payloadHash = fragmentWireHash(tree)
        return .success(try deliverFragment(record, deviceId: deviceId, payloadHash: payloadHash))
    }

    private func putFragment(_ request: HubRequest, urlId: String) -> HubResponse {
        guard let body = request.body,
            let parsed = try? JSONDecoder().decode(PutFragmentBody.self, from: body),
            let fragmentData = try? JSONEncoder.learningCore().encode(parsed.fragment),
            let record = try? JSONDecoder.learningCore().decode(FragmentRecord.self, from: fragmentData)
        else {
            return .json(422, ["error": "INVALID_BODY"])
        }
        guard !urlId.isEmpty, urlId == record.id else {
            return .json(422, ["error": "ID_MISMATCH"])
        }
        do {
            switch try parseAndDeliverFragmentTree(parsed.fragment, deviceId: parsed.deviceId) {
            case .failure(.invalid(let code)):
                return .json(422, ["error": code])
            case .success(.created(let revision, let hash)):
                return .json(201, ["id": urlId, "revision": revision, "hash": hash])
            case .success(.applied(let revision, let hash)):
                return .json(200, ["applied": true, "revision": revision, "hash": hash])
            case .success(.unchanged(let stale, let revision, let hash)):
                var object: [String: Any] = [
                    "applied": false,
                    "revision": revision,
                    "hash": hash,
                ]
                if stale { object["currentRevision"] = revision }
                return .json(200, object)
            case .success(.conflict):
                return .json(409, ["error": "conflict"])
            case .success(.deleted):
                return .json(410, ["error": "deleted"])
            }
        } catch {
            return .json(500, ["error": "storage error"])
        }
    }

    // ── PUT /v1/assets/{id} (storage.md §8) ──────────────────────────────

    private func putAsset(_ request: HubRequest, urlId: String) -> HubResponse {
        guard !urlId.isEmpty else { return .json(404, ["error": "not found"]) }
        let bytes = request.body ?? Data()

        guard let lengthText = request.headers["x-annhub-byte-length"],
            let headerLength = Int(lengthText.trimmingCharacters(in: .whitespaces)),
            headerLength > 0
        else { return .json(422, ["error": "byte_length_invalid"]) }
        guard bytes.count == headerLength else {
            return .json(422, ["error": "byte_length_mismatch"])
        }
        if headerLength > MAX_IMAGE_BYTES {
            return .json(413, ["error": "payload too large"])
        }

        let mime =
            (request.headers["content-type"] ?? "")
            .split(separator: ";").first.map { $0.trimmingCharacters(in: .whitespaces) } ?? ""
        guard ImageMimeType(rawValue: mime) != nil else {
            return .json(422, ["error": "mime_type_invalid"])
        }

        guard let headerSha = request.headers["x-annhub-sha256"]?.trimmingCharacters(in: .whitespaces),
            !headerSha.isEmpty
        else { return .json(422, ["error": "sha256_missing"]) }
        let actualSha = sha256Hex(bytes)
        guard actualSha == headerSha.lowercased() else {
            return .json(422, ["error": "sha256_mismatch"])
        }

        // R1 does not decode image bytes; width/height stay 0 until a decoder
        // ships (no PNG parsing required by the contract tests).
        let asset = ImageAsset(
            id: urlId,
            mimeType: mime,
            byteLength: bytes.count,
            sha256: actualSha,
            width: 0,
            height: 0,
            createdAt: Int(Date().timeIntervalSince1970 * 1000)
        )

        do {
            // Check-then-insert: concurrent uploads of one id answer 201 once, then 200/409.
            return try store.exclusive { () throws -> HubResponse in
                if let existing = try store.getAsset(id: urlId) {
                    if existing.metadata.sha256 == actualSha {
                        return .json(
                            200,
                            [
                                "id": urlId,
                                "byteLength": existing.metadata.byteLength,
                                "sha256": existing.metadata.sha256,
                            ])
                    }
                    return .json(409, ["error": "conflict"])
                }
                _ = try store.putAsset(asset, bytes: bytes)
                return .json(
                    201,
                    [
                        "id": urlId,
                        "byteLength": bytes.count,
                        "sha256": actualSha,
                    ])
            }
        } catch {
            return .json(500, ["error": "storage error"])
        }
    }

    // ── POST /v1/events (storage.md §9, idempotent per (deviceId,eventId)) ─

    struct EventBatchDecoding: Decodable {
        var deviceId: String
        var events: [EventEntry]
    }

    struct EventEntry: Decodable {
        var eventId: String
        var type: String
        var payload: WireValue
        var createdAt: Int
    }

    private func bumpEvents(_ mutate: (inout EventsStats) -> Void) {
        withLock { mutate(&eventsStats) }
    }

    private func postEvents(_ request: HubRequest) -> HubResponse {
        guard let body = request.body,
            let batch = try? JSONDecoder().decode(EventBatchDecoding.self, from: body),
            !batch.deviceId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else {
            return .json(422, ["error": "INVALID_BODY"])
        }
        bumpEvents { $0.received += batch.events.count }

        var applied = 0
        var duplicates = 0
        var skipped: [[String: String]] = []

        func skip(_ eventId: String, _ reason: String) {
            skipped.append(["eventId": eventId, "reason": reason])
        }

        for event in batch.events {
            do {
                if try store.isApplied(deviceId: batch.deviceId, eventId: event.eventId) {
                    duplicates += 1
                    bumpEvents { $0.duplicates += 1 }
                    continue
                }
                let stored: Bool
                switch event.type {
                case "fragment.created", "fragment.updated":
                    switch try parseAndDeliverFragmentTree(event.payload, deviceId: batch.deviceId) {
                    case .failure(.invalid(let code)):
                        skip(event.eventId, code)
                        stored = false
                    case .success(.conflict):
                        // Same revision, different payload — surface, never
                        // silently overwrite (storage.md §9).
                        skip(event.eventId, "CONFLICT")
                        stored = false
                    case .success(.deleted):
                        skip(event.eventId, "LOCAL_DELETED")
                        stored = false
                    case .success:
                        stored = true
                    }
                case "review.rated":
                    guard let payloadData = try? JSONEncoder.learningCore().encode(event.payload),
                        let rated = try? JSONDecoder.learningCore().decode(ReviewRatedPayload.self, from: payloadData)
                    else {
                        skip(event.eventId, "INVALID")
                        stored = false
                        break
                    }
                    guard try store.getFragment(id: rated.fragmentId) != nil else {
                        skip(event.eventId, "UNKNOWN_FRAGMENT")
                        stored = false
                        break
                    }
                    try store.applyExternalReview(
                        fragmentId: rated.fragmentId, review: rated.review, log: rated.log
                    )
                    stored = true
                default:
                    skip(event.eventId, "UNKNOWN_TYPE")
                    stored = false
                }
                // Applied markers are written only for events that stored.
                if stored {
                    _ = try store.markApplied(deviceId: batch.deviceId, eventId: event.eventId)
                    applied += 1
                    bumpEvents { $0.applied += 1 }
                } else {
                    bumpEvents { $0.skipped += 1 }
                }
            } catch {
                skip(event.eventId, "STORAGE_ERROR")
                bumpEvents { $0.skipped += 1 }
            }
        }
        return .json(
            200,
            [
                "applied": applied,
                "duplicates": duplicates,
                "skipped": skipped,
            ])
    }

    // ── GET /v1/changes?cursor=<int>&limit=<int> (storage.md §9) ─────────

    private func getChanges(_ request: HubRequest) -> HubResponse {
        let items = URLComponents(string: request.path)?.queryItems ?? []
        var cursor = 0
        var limit = 200
        for item in items {
            switch item.name {
            case "cursor": cursor = Int(item.value ?? "") ?? 0
            case "limit": limit = Int(item.value ?? "") ?? 200
            default: break
            }
        }
        limit = min(max(1, limit), 1000)

        do {
            let rows = try store.changes(after: max(0, cursor), limit: limit)
            var changes: [[String: Any]] = []
            for row in rows {
                var object: [String: Any] = [
                    "seq": row.seq,
                    "type": row.type,
                ]
                if let data = row.payloadJson.data(using: .utf8),
                    let payload = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
                {
                    for (key, value) in payload {
                        object[key] = value
                    }
                }
                changes.append(object)
            }
            var response: [String: Any] = ["changes": changes]
            if let lastSeq = rows.last?.seq {
                response["nextCursor"] = lastSeq
                // Approximate pending-queue bookkeeping for the system page:
                // the extension has pulled everything up to the page end.
                store.setPulledCursor(lastSeq)
            }
            return .json(200, response)
        } catch {
            return .json(500, ["error": "storage error"])
        }
    }
}
