/**
 * Written / academic high-frequency baseline (S3, research doc B10).
 *
 * The primary frequency table is built from OpenSubtitles (spoken/dialogue corpus), which
 * systematically under-counts written/academic vocabulary: connectives and academic words
 * a B1/B2 reader meets constantly in news and essays (furthermore, whereas, paradigm,
 * methodology) land in high "rare" bands and get annotated as if unknown — while spoken
 * fillers (gonna, dude, yeah) sit in band 1. This list corrects that bias.
 *
 * Source/method: hand-curated from well-established written/academic high-frequency sets
 *   — academic connectives/discourse markers, the Academic Word List (AWL) sublist 1–2
 *     headwords, and New General Service List (NGSL) written-register staples. These are
 *     words a learner at/above the lower-intermediate written level is expected to know,
 *     so the difficulty gate should treat them as "known" (skip), not surface them.
 *
 * Scope: lookup-only, lowercased lemmas. NOT a difficulty ranking — membership alone
 *   means "treat as known written vocabulary". Inflected forms are resolved to a lemma by
 *   the caller (pickLemma) before lookup, same as the frequency table.
 *
 * This is intentionally small and high-precision: only words whose subtitle-frequency band
 * clearly misrepresents how common they are in written English. Genuinely hard academic
 * terms (epistemic, perfunctory) are deliberately excluded so they still get annotated.
 */

const WRITTEN_HIGH_FREQUENCY: ReadonlySet<string> = new Set([
  // ── Academic / formal connectives & discourse markers ──
  'furthermore',
  'moreover',
  'whereas',
  'thereby',
  'thereof',
  'therein',
  'wherein',
  'whereby',
  'hereby',
  'herein',
  'nonetheless',
  'nevertheless',
  'notwithstanding',
  'albeit',
  'henceforth',
  'hitherto',
  'whilst',
  'hence',
  'thus',
  'therefore',
  'consequently',
  'accordingly',
  'subsequently',
  'meanwhile',
  'likewise',
  'conversely',
  'alternatively',
  'additionally',
  'specifically',
  'notably',
  'namely',
  'regardless',
  'aforementioned',
  'respectively',
  'insofar',
  'thereafter',
  'beforehand',

  // ── AWL sublist 1 headwords (high-frequency academic core) ──
  'analyse',
  'analysis',
  'approach',
  'area',
  'assess',
  'assessment',
  'assume',
  'authority',
  'available',
  'benefit',
  'concept',
  'consist',
  'context',
  'contract',
  'create',
  'data',
  'define',
  'definition',
  'derive',
  'distribute',
  'economy',
  'environment',
  'establish',
  'estimate',
  'evident',
  'export',
  'factor',
  'finance',
  'financial',
  'formula',
  'function',
  'identify',
  'income',
  'indicate',
  'individual',
  'interpret',
  'involve',
  'issue',
  'labour',
  'legal',
  'legislate',
  'major',
  'method',
  'occur',
  'percent',
  'period',
  'policy',
  'principle',
  'proceed',
  'process',
  'require',
  'research',
  'respond',
  'role',
  'section',
  'sector',
  'significant',
  'similar',
  'source',
  'specific',
  'structure',
  'theory',
  'vary',
  'variable',

  // ── AWL sublist 2 headwords ──
  'achieve',
  'acquire',
  'administrate',
  'affect',
  'appropriate',
  'aspect',
  'assist',
  'category',
  'chapter',
  'commission',
  'community',
  'complex',
  'compute',
  'conclude',
  'conduct',
  'consequent',
  'construct',
  'consume',
  'credit',
  'culture',
  'design',
  'distinct',
  'element',
  'equate',
  'evaluate',
  'feature',
  'final',
  'focus',
  'impact',
  'injure',
  'institute',
  'invest',
  'item',
  'journal',
  'maintain',
  'normal',
  'obtain',
  'participate',
  'perceive',
  'positive',
  'potential',
  'previous',
  'primary',
  'purchase',
  'range',
  'region',
  'regulate',
  'relevant',
  'reside',
  'resource',
  'restrict',
  'secure',
  'seek',
  'select',
  'site',
  'strategy',
  'survey',
  'text',
  'tradition',
  'transfer',

  // ── Written-register academic staples (methodology / argumentation) ──
  'paradigm',
  'methodology',
  'methodological',
  'empirical',
  'hypothesis',
  'framework',
  'criterion',
  'criteria',
  'phenomenon',
  'rationale',
  'premise',
  'inherent',
  'implicit',
  'explicit',
  'comprise',
  'constitute',
  'underlying',
  'pertain',
  'attribute',
  'correlate',
  'denote',
  'encompass',
  'entail',
  'paramount',
  'predominant',
  'prevalent',
  'substantial',
  'sufficient',
  'feasible',
  'viable',
])

/** Whether a (lowercased, lemmatized) word is a written/academic high-frequency word. */
export function isWrittenHighFrequencyWord(word: string): boolean {
  if (!word) return false
  return WRITTEN_HIGH_FREQUENCY.has(word)
}

export const __testing = {
  size: WRITTEN_HIGH_FREQUENCY.size,
}
